### ISSUE TITLE
Mac OS - When I hover on a tab this happens

### ISSUE THREAD

**Issue by teeshow** [QNetITQ/WaveFox#10]
When I hover on a tab this happens - <img width="296" alt="Report" src="https://user-images.githubusercontent.com/88216892/132138904-cdeefb68-bb8c-433b-a83f-52a963713932.png">

**Comment by QNetITQ** [comment]
Hi. It looks like you haven't followed all the installation steps. This happens if you do not include "layout.css.color-mix.enabled"

**Comment by teeshow** [comment]
@QNetITQ Oh. Okay, thanks!

**Comment by QNetITQ** [comment]
If your problem is resolved, please close the bug report.

**Comment by teeshow** [comment]
Uh how
