### ISSUE TITLE
Chrome-style close buttons are too large

### ISSUE THREAD

**Issue by contextnerror** [QNetITQ/WaveFox#101]
The close tab buttons on the Chrome tabs are bigger than they are in Chrome. Because of this, when using reduced minimum tab sizes (a la chrome), the close buttons float off the tabs.
![Screen Shot 2023-01-09 at 6 58 04 PM](https://user-images.githubusercontent.com/54487525/211451833-b65e5f4e-7e55-43d3-8618-0598945d3190.png)
![Screen Shot 2023-01-09 at 6 58 14 PM](https://user-images.githubusercontent.com/54487525/211451842-2daa637e-1756-4543-825a-d4babf337b17.png)

**Comment by QNetITQ** [comment]
This style is not intended to accurately reproduce the look and feel of Google Chrome. I'll see what I can do, but I can't promise anything.
