### ISSUE TITLE
Linux Transparency 'ghost' effect

### ISSUE THREAD

**Issue by MuriloucoLouco** [QNetITQ/WaveFox#102]
I'm using Manjaro KDE (KDE Plasma version 5.26.4), X11, Firefox version 108.0.1. I'm not using Kwin forceblur, but if i use it, the problem remains.  I have a AMD Ryzen 3 2200G CPU, with AMD Radeon Vega 8 integrated GPU. Kernel is 6.1.1-1-MANJARO.

From what i've understood, when i resize firefox, the toolbar gets transparent for an instant, and then quickly "layers" of semi-transparent white are printed on top of it, until the toolbar is completly opaque. Like when you forget to clear the canvas in js, but in this case, it's semi-transparent, so it creates a ghost effect.

I tried changing many gfx settings on about:config to see if it fixes something, like changing to software rendering, and some random settings, but nothing seems to work. Maybe this is something related to the compositor? 

Also, other firefox themes that have this toolbar transparency also suffer from the same problem.

![ghost](https://user-images.githubusercontent.com/58440129/212746653-9d71bbbf-3936-4479-8861-0fa05ecd5494.gif)

**Comment by luisbocanegra** [comment]
You need to restart KWin after enabling the Force Blur script with this command: `kwin_x11 --replace` alternatively you can logout/login, May also need to check the `Only blur the content of the window` option in the script configuration, and make sure the class name is correct if you're blurring matching windows only.

**Comment by luisbocanegra** [comment]
You will also face the issue #82 when the Firefox window isn't on top of/close to another blurred window

**Comment by MuriloucoLouco** [comment]
The problem doesn't seem to be related to the kwin blur script, given that it occurs even when it's not enabled.  Indeed, restarting kwin did not solve the problem. Enabling the blur makes the ghost effect less evident, but i can still see it when i drag the window quickly, and for an instant i can see it transparent, until the semi-transparent layers start covering it becoming completely opaque white.

**Comment by QNetITQ** [comment]
Everything works.
![изображение](https://user-images.githubusercontent.com/85301851/212771919-1199bb1e-7920-43de-a8a8-734c4d16c82d.png)
Double-check that all installation steps have been completed. If it does not help, then something individual, for example, drivers or some own settings related to hardware acceleration.

**Comment by luisbocanegra** [comment]
Run this command: `xprop _KDE_NET_WM_BLUR_BEHIND_REGION` should print something like this:

```
_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 0, 0, 1920, 1048
```

If it doesn't then you have something miss configured, also you must close all firefox windows as the effect doesn't apply to existing ones after reloading kwin, or again, you can just reboot :)

**Comment by MuriloucoLouco** [comment]
> Everything works. ![изображение](https://user-images.githubusercontent.com/85301851/212771919-1199bb1e-7920-43de-a8a8-734c4d16c82d.png) Double-check that all installation steps have been completed. If it does not help, then something individual, for example, drivers or some own settings related to hardware acceleration.

Any idea where i might find something related? Tried disabling the hardware acceleration on firefox, but it doesn't change anything.

> Run this command: `xprop _KDE_NET_WM_BLUR_BEHIND_REGION` then select a firefox window, it should print something like this:
> 
> ```
> _KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 0, 0, 1920, 1048
> ```
> 
> If it doesn't then you have something miss configured, also you must close all firefox windows as the effect doesn't apply to existing ones after reloading kwin, or again, you can just reboot :)

The output is `_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 0, 0, 1882, 1080`

**Comment by MuriloucoLouco** [comment]
Ok, i found a partial solution. If i change from X11 to Wayland, the transparency works perfectly. My guess is that when i installed Wayland, it changed some configuration that affects X11, but i'm a noob in this topic. Still, wayland is too glitchy to be used at the moment, so i need to find the fix to X11

**Comment by QNetITQ** [comment]
I can't help here. Transparency on Linux relies on an experimental key (**gfx.webrender.all**) that depends on hardware acceleration and everything related to it. The behavior may differ depending on the driver or even GPU vendor.

**Comment by luisbocanegra** [comment]
> The output is `_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 0, 0, 1882, 1080`

Does Force Blur work for other programs?

If it doesn't you may have better luck asking in the force blur repo: https://github.com/esjeon/kwin-forceblur

> Ok, i found a partial solution. If i change from X11 to Wayland, the transparency works perfectly. My guess is that when i installed Wayland, it changed some configuration that affects X11, but i'm a noob in this topic. 
> Still, wayland is too glitchy to be used at the moment, so i need to find the fix to X11

FYI Force blur relies on x11 blur region thing and there is no wayland equivalent (yet) so you have transparency only.

**Comment by MuriloucoLouco** [comment]
> Does Force Blur work for other programs?
It does work, and while i was testing it on konsole, suddenly the ghosting stopped, except for a small rectangle. At first it happened only when konsole was open and blurred (as you can see by what i wrote originally in the image), but it continued even after i closed everything, disabled forceblur and restarted firefox:
![Screenshot_20230117_113544](https://user-images.githubusercontent.com/58440129/212943482-3217d7f5-050e-4d95-8665-8aea261578c2.png)

**Comment by QNetITQ** [comment]
Try raising the background blur level. This bug appeared after updating to kde 5.25

**Comment by MuriloucoLouco** [comment]
> Try raising the background blur level. This bug appeared after updating to kde 5.25

How do i do that?

**Comment by luisbocanegra** [comment]
> Try raising the background blur level. This bug appeared after updating to kde 5.25

Oh this is it, after lowering it here i can reproduce this exact glitch!

**Comment by luisbocanegra** [comment]
> > Try raising the background blur level. This bug appeared after updating to kde 5.25
> 
> How do i do that?

System settings > Workspace Behavior > Blur > Ramp up blur strength

**Comment by MuriloucoLouco** [comment]
Yep, it works! Weird bug, i wouldn't expect the blur strength to affect it even when the forceblur isn't activated. I'll close the issue.
