### ISSUE TITLE
How can I make this work for google chrome?

### ISSUE THREAD

**Issue by bigplayer-ai** [QNetITQ/WaveFox#103]
How can I make this work for google chrome?

**Comment by bigplayer-ai** [comment]
Any other workarounds for google chrome?On 20 Jan 2023, at 19:14, QNetITQ ***@***.***> wrote:﻿
No way. The ability to use CSS styles is only available on Firefox.

**Comment by QNetITQ** [comment]
Maybe they are, but I don't know anything about it.
