### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZerOneSeven** [QNetITQ/WaveFox#105]
Close, Maximize, Minimize are showing up twice when i hover over them.
Only shows up when i have transparency active i'm also using "Mica For Everyone"

![Screenshot_20230123_030312](https://user-images.githubusercontent.com/105567571/213991486-84ffa562-52c8-4384-bc45-4152b55c4c17.png)

**Comment by ZerOneSeven** [comment]
ah, k

**Comment by Deathbyteacup** [comment]
I've fixed this using CSS here; https://github.com/QNetITQ/WaveFox/issues/113#issuecomment-1474925989
