### ISSUE TITLE
Tabs and window controls out of window (inaccessible) when bookmark toolbar is enable in OneLine mode

### ISSUE THREAD

**Issue by kujou-kju** [QNetITQ/WaveFox#109]
I recently reset my Notebook and modified my Firefox with WaveFox since I used it on my PC already. Everything worked fine.
When I was back on my PC I updated WaveFox since my Browser used an older Version with the older ` userchrome ` strings and added the new ones (same settings as on my Notebook)

Now I have the problem that the adress bar gets so big that I cannot use my tabs anymore and the window controls are also out of window. However this occurs only when I have the bookmark toolbar enabled. I usually have it show up on new tabs only. I didn't had this issue on my Notebook but there were almost no bookmarks in the toolbar in.

<details><summary>Screenshots</summary>

![grafik](https://user-images.githubusercontent.com/23724383/216970240-e29019ba-402b-42c6-9c8e-7bd4ba442332.png)
OneLine mode without bookmark toolbar active

![grafik](https://user-images.githubusercontent.com/23724383/216970299-5437553f-0ca8-4db5-b36e-0a8d7ef528a9.png)
OneLine mode with bookmark toolbar active (new tab page)

</details>

<details><summary>Details</summary>

### Browser / OS

Firefox Version: 109.0.1 (64-Bit)
OS: Windows 11 Pro 22H2

### Relevant Settings

| WaveFox Preference | Value |
| --- | --- |
| userChrome.OneLine.NavBarFirst.Enabled | true |
| userChrome.OneLine.TabBarFirst.Enabled | false |
| userChrome.ProtonTabs-Enabled | true |
| userChrome.RegularMenuIcons-Enabled | true |
| userChrome.Toolbar.Transparency.High.Enabled | false |
| userChrome.Toolbar.Transparency.Medium.Enabled | false |
| userChrome.Toolbar.Transparency.VeryHigh.Enabled | true |
| userChrome.Windows.SystemEffects.Enabled | true |

| Firefox Preference | Value |
| --- | --- |
| toolkit.legacyUserProfileCustomizations.stylesheets | true |
| gfx.webrender.all | true |
| browser.tabs.inTitlebar | 2 (unmodified) |
| browser.toolbars.bookmarks.visibility | newtab |

</details>

**Comment by QNetITQ** [comment]
Indeed, when the bookmarks bar overflows, such a problem occurs. I fixed it, but it's not the final version. When I have free time, I will find a better way.

**Comment by QNetITQ** [comment]
All is ready.

**Comment by roberthawdon** [comment]
I'm still having this issue on WaveFox v1.6.126 on macOS

**Comment by QNetITQ** [comment]
I made the necessary corrections in v1.6.127. It should be fine now.

**Comment by roberthawdon** [comment]
Thanks, that's working great now!
