### ISSUE TITLE
Thin line between tabs and toolbar

### ISSUE THREAD

**Issue by Krissh-C** [QNetITQ/WaveFox#114]
Small bug but there is a small line between the tabs and the toolbar as seen in the screenshot. It's present with all styles except Proton of course.
![image](https://user-images.githubusercontent.com/117280851/219953605-4e7338c4-418f-4eef-a71d-0663652646fc.png)

**Comment by QNetITQ** [comment]
Can't reproduce your problem. Did you make your own style changes?

**Comment by Krissh-C** [comment]
No worries. Fixed it by moving the toolbar and bookmarks menu up. It is a combination of Wavefox and [Firefox Mod Blur](https://github.com/datguypiko/Firefox-Mod-Blur) so that might've been the reason.
