### ISSUE TITLE
Regular Menu Icons use the wrong color when using dark theme macOS

### ISSUE THREAD

**Issue by trbatukim** [QNetITQ/WaveFox#115]
<img width="355" alt="Ekran Resmi 2023-02-22 16 27 03" src="https://user-images.githubusercontent.com/99345193/220633743-d78d915c-9632-4dbe-b59e-4ac0f2598618.png">

**Comment by QNetITQ** [comment]
You're right. The issue is Mac exclusive. Activate the key `svg.context-properties.content.enabled`
