### ISSUE TITLE
How can I disable the tab separator?

### ISSUE THREAD

**Issue by Irastris** [QNetITQ/WaveFox#12]
I'm not a fan of the little line that appears between each tab while using this userChrome. Is there a fix I can perform to remove it, akin to the native Proton interface?

**Comment by QNetITQ** [comment]
Hi. Delete everything in the "Separators" section

**Comment by Irastris** [comment]
Fantastic, thank you for all your work!

**Comment by kocane** [comment]
@QNetITQ what should I adjust to only hide the first seperator? Previously I used the code below in the very top of userChrome.css but it seemed to stop working with the latest version.

```
.tabbrowser-tab[first-visible-unpinned-tab]::before
{
background-color: transparent !important;
}
```

**Comment by QNetITQ** [comment]
.tabbrowser-tab[first-visible-unpinned-tab]::before
{
    opacity: 0 !important;
}
I will probably add the ability to remove this separator without additional code
