### ISSUE TITLE
Shadow/border keys don't seem to be taking effect on any theme

### ISSUE THREAD

**Issue by Merconix** [QNetITQ/WaveFox#121]
For reference, I am using Firefox v111.0 on Windows 11, perhaps I'm misinterpreting the usage of these keys:
-userChrome.LightTheme.TabFrameType.Shadow.Enabled
-userChrome.LightTheme.TabFrameType.Border.Enabled 

I'm trying to achieve a shadow around the UI, ultimately similar to what is shown on this issue: https://github.com/QNetITQ/WaveFox/issues/56
However, regardless of the keys I set or the style in-use, no such shadows appear, for example:
![image](https://user-images.githubusercontent.com/41351832/225601496-e8240307-d0ad-4d3a-8df7-f3f40073c7e6.png)

**Comment by QNetITQ** [comment]
You only specified the type. You also need to specify the color and saturation. Everything is written in the description.

**Comment by Merconix** [comment]
Entirely correct! Massive oversight on my part, assuming there'd be a default.
Thanks for the clarification,
