### ISSUE TITLE
WaveFox tabs on MacOS are broken

### ISSUE THREAD

**Issue by mr00z** [QNetITQ/WaveFox#126]
Hey, it seems like WaveFox tabs on Firefox v113.0b1 (64-bit) on MacOS are broken. Here is a screenshot:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/22932530/231233315-3636ed2c-9987-4fcb-aa64-5d287d8d7fdf.png">

**Comment by QNetITQ** [comment]
At the moment it is broken on all systems. I was going to make some changes related to tabs. I'll do it when I have time.

**Comment by mr00z** [comment]
Sure, thanks!

**Comment by yujinlin0224** [comment]
I am using https://github.com/QNetITQ/WaveFox/tree/19359e48fdc19b4238a6ffd7d90625803daa8a65 version and it works fine to me.

**Comment by QNetITQ** [comment]
The release with fixes has been deployed, but wait for the release of Firefox 113.
