### ISSUE TITLE
New Tab Shapes (WaveFox v1.6.113/114)

### ISSUE THREAD

**Issue by QNetITQ** [QNetITQ/WaveFox#127]
The new keys are listed below

- userChrome.TabCorners.Option1.Enabled
- userChrome.TabCorners.Option2.Enabled
- userChrome.TabCorners.Option3.Enabled
- userChrome.TabCorners.Option4.Enabled
- userChrome.TabCorners.Option5.Enabled
- userChrome.TabCorners.Option6.Enabled
- userChrome.TabCorners.Option7.Enabled
- userChrome.TabCorners.Option8.Enabled
- userChrome.TabCorners.Option9.Enabled
- userChrome.TabCorners.Option10.Enabled
- userChrome.TabCorners.Option11.Enabled
- userChrome.TabCorners.Option12.Enabled
- userChrome.TabCorners.Option13.Enabled
- userChrome.TabCorners.Option14.Enabled
- userChrome.TabCorners.Option15.Enabled
- userChrome.TabCorners.Option16.Enabled

**Comment by davidbepo** [comment]
hi, been using this theme for a while now
but why this change?
i think the new names are far less descriptive and even if they werent this would force users to change prefs

**Comment by QNetITQ** [comment]
I agree, the names are not very good. But given that the user installs once and forgets for at least half a year, then it's normal.

**Comment by TheInsane101** [comment]
I liked these options. It wasn't necessary to remove them.

**Comment by QNetITQ** [comment]
Chopped corners now look out of place. Other tab shapes are interchangeable.
