### ISSUE TITLE
I don't know what i did but the tab icons and text don't fit inside the tab

### ISSUE THREAD

**Issue by ihopeidieinafire141** [QNetITQ/WaveFox#129]
Firefox 112.01

**Comment by QNetITQ** [comment]
I see people for the most part download beta instead of release. This is a problem because it has a lot of bugs. Download [release](https://github.com/QNetITQ/WaveFox/releases).

**Comment by ihopeidieinafire141** [comment]
I have downloaded the release version i'm pretty sure

**Comment by ihopeidieinafire141** [comment]
![image](https://user-images.githubusercontent.com/121703210/232896180-37d759f5-dda0-43f1-98b3-3c6c7a088e03.png)

**Comment by QNetITQ** [comment]
In this case, I mean style. Download the release version from the link I left in the post above. I think this should solve your problem. If not, then write here.

**Comment by ihopeidieinafire141** [comment]
Oh. I'm sorry
