### ISSUE TITLE
Old container indicator

### ISSUE THREAD

**Issue by kocane** [QNetITQ/WaveFox#13]
The new indicator is pretty cool and well made, but in my work I use containers alot and the old indicator kind of worked better for me.

Any chance for a switch so one can choose which to use?

**Comment by QNetITQ** [comment]
Hi. Let's do it this way. Use this option for one week, it just seems to me that it's a matter of habit. I moved the indicator settings to the customization section. If you don't get used to it in a week, I will return the old container design. Only the size of the indicators should be an even value. I forgot to write about it, then I will add

**Comment by kocane** [comment]
Deal ;-)

**Comment by QNetITQ** [comment]
I will adjust the parameters of the container indicators according to the screenshot
![изображение](https://user-images.githubusercontent.com/85301851/133111923-80245ecc-f703-4ae6-ba33-fd9beba5a312.png)

**Comment by QNetITQ** [comment]
Although you can consider this option, but only for regular tabs. Does it make sense, I don’t know 
![изображение](https://user-images.githubusercontent.com/85301851/133112705-7b0fe8cf-0e4b-4d91-89f1-990f583e3deb.png)

**Comment by kocane** [comment]
Latter screenshot actually looks pretty cool. But regardless, the squaring of the indicator is a nice change imo.

**Comment by QNetITQ** [comment]
Two options to choose from
![изображение](https://user-images.githubusercontent.com/85301851/133132220-4ef4643d-96ea-4bd8-9f6d-c014496770f2.png)
or
![изображение](https://user-images.githubusercontent.com/85301851/133132486-2eec090d-09e1-443b-9fd7-dff97ca52b82.png)

**Comment by kocane** [comment]
I'm curious how the bottom one will look with my theme:
![image](https://user-images.githubusercontent.com/7694813/133132988-47271218-627f-4737-bd96-9362c18ca470.png)

**Comment by QNetITQ** [comment]
![изображение](https://user-images.githubusercontent.com/85301851/133133651-42df94cf-5e1d-4c00-90a3-c241779e3e65.png)

**Comment by QNetITQ** [comment]
In general, a week has passed. Should I return the old container indicators or keep these?

**Comment by kocane** [comment]
@QNetITQ I personally still prefer the old style indicators.

**Comment by QNetITQ** [comment]
I returned the old indicators.

**Comment by QNetITQ** [comment]
I think the question has been cleared. I am closing a bug report
