### ISSUE TITLE
Development request for v1.6

### ISSUE THREAD

**Issue by DeepTulip** [QNetITQ/WaveFox#131]
I'm still using version 87 of Firefox, and I really like its theme.
This is its default theme, following the system color scheme.
![avatar](https://i.imgur.com/QbXrsQZ.png)
Yes, this is not a dark theme.
I can't stand the current bright and dark themes. The bright theme is too dazzling, and the dark theme is too gloomy.
And this theme is neither bright nor dark, like a grove of trees with long shadows under the sun.
Can v1.6 add a version that replicates this theme? Thank you very much.

**Comment by QNetITQ** [comment]
I think that for this it is enough to put the theme ([Photon Colors](https://addons.mozilla.org/ru/firefox/addon/photon-colors/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)) from the repository.

**Comment by DeepTulip** [comment]
Thank you very much This is just what I need.
