### ISSUE TITLE
Windows 11 Mica/Acrylic showing as black

### ISSUE THREAD

**Issue by RibShark** [QNetITQ/WaveFox#132]
![image](https://user-images.githubusercontent.com/1957489/233610550-8025dd00-6239-4212-aaa8-1bbe69be4285.png)
As you can see in the image above, I have all the settings showing correctly but WaveFox is simply showing black where there should be Mica/Acrylic. I'm using Firefox 113.0b6 and Windows 11 22624.1610 (note that I got A/B enrolled into the Windows test to automatically show Mica on all titlebars even if MicaForEveryone isn't installed, but I installed it anyway just to make sure).

**Comment by QNetITQ** [comment]
Everything works. Check the app settings
![изображение](https://user-images.githubusercontent.com/85301851/233615679-171f5af5-0afc-4ad2-a9e0-741017e24c40.png)

**Comment by RibShark** [comment]
I have set the settings exactly the same way as you and it still shows as black.

**Comment by QNetITQ** [comment]
A black browser frame (Dark theme) indicates that transparency is active. So something is interfering. Check if transparency is enabled in Windows. Disable programs related to system customization, if installed. The accent color must be disabled in the system. Hardware acceleration must also be enabled both in the system and in the browser.

**Comment by RibShark** [comment]
Figured out the issue. Firefox disables DirectComposition on NVIDIA GPUs if two monitors are connected with different refresh rates ("Blocklisted; failure code NVIDIA_REFRESH_RATE_MIXED"). It seems DirectComposition is necessary in order to get these effects working. So it might be a good idea to add to the readme that if it doesn't work, make sure all monitors have the same refresh rate set.
