### ISSUE TITLE
Tab Separator not showing with containers

### ISSUE THREAD

**Issue by Minibus93** [QNetITQ/WaveFox#136]
Hello, 

first of all I would like to show appreciation for the tab shape of 

`userChrome.TabCorners.Option10.Enabled`

since I read that some shape may be removed based on appreciation I thought it was a good idea to let you know that I really appreciation this option (I think this was the previous "edge" style)

After this, I would like to report that tab separators don't seem to work between containers tabs (they don't show) even if 

`userChrome.TabSeparatorsMediumSaturation-Enabled`

is enabled.

My system info are:
FF113 stable release channel
Win10 22h2

Oh, and one last question: where is the folder named "v1.6.116" that is present in the .zip file of the 113 release supposed to go? in the chrome folder as usual? 

Thanks for making WaveFox, I really appreciate your hard work!

**Comment by QNetITQ** [comment]
I originally wanted to keep all the changes for v1.6.116, but later changed my mind, as users of Firefox 115 ESR will have to use the style for more than a year. To reduce fragmentation between styles, I decided to make the changes that are possible in v1.6.114. This version will most likely become v1.6.115 ESR. I want to use a month in reserve to find bugs and fix them. In v1.6.116 it is planned to remove support for Windows 7/8 and ecotic tab layouts. Everything else has already been removed in v1.6.114. As for the tab separators, they should not be displayed if the container is active, since the containers already have a background.

**Comment by Minibus93** [comment]
> I originally wanted to keep all the changes for v1.6.116, but later changed my mind, as users of Firefox 115 ESR will have to use the style for more than a year. To reduce fragmentation between styles, I decided to make the changes that are possible in v1.6.114. This version will most likely become v1.6.115 ESR. I want to use a month in reserve to find bugs and fix them. In v1.6.116 it is planned to remove support for Windows 7/8 and ecotic tab layouts. Everything else has already been removed in v1.6.114.

I see, it makes sense! That a nice way of thinking in my opinion!

> As for the tab separators, they should not be displayed if the container is active, since the containers already have a background. 

Argh, I have modified the code to disable the container background as that was too colorful for me, do you happen to know if there's any "on the fly" way to have separators showing with containers? 
Only if it isn't too much work to think on, of course!

> I corrected the description in the release to the current one.

Thanks! I think it will be a great clarification as most stable release channel are approaching to FF113 just today, right now.

**Comment by QNetITQ** [comment]
If you want, you can put directly into 1.6.114. Although it is marked as beta, I already made all the changes I wanted there. It is fully compatible with version 113 of the browser. The only thing I didn't do was remove the old svg set, but otherwise the style is ready for browser version 114.

**Comment by QNetITQ** [comment]
> Argh, I have modified the code to disable the container background as that was too colorful for me, do you happen to know if there's any "on the fly" way to have separators showing with containers?
> Only if it isn't too much work to think on, of course!

Delete this [line](https://github.com/QNetITQ/WaveFox/blob/fb18276509d592a3c99d52dde5e99087ef342afe/chrome/userChrome.css#L1091).

**Comment by Minibus93** [comment]
Much appreciated! Thanks a lot!

**Comment by TerraZ-UO** [comment]
> Argh, I have modified the code to disable the container background as that was too colorful for me
@Minibus93, can you please specify how exactly you achieved this? I don't like coloured container tabs as well.

**Comment by Minibus93** [comment]
@QNetITQ Hi! I saw the comment by my notification bar on my phone, but I can't see it anymore so I'm not sure if you still need it (and I'm not sure if I remember it all lol).

Anyway, it was about containers, so sure, I'll try to give as much details as possible on how fir them into WaveFox.

I'm not the author of the code for this style of containers, I just saw them somewhere and frankensteined it into WaveFox (I may have changed something for the FF113 update out of the original code, but that's about it)

Anyway, so:

1) Delete the "Container Indicators" section in the WaveFox css file;
2) add this code instead:

`/* rework of container style */
.tab-context-line {
  order: 1 !important;
  opacity: 1 !important;
  transition: none !important;
}`

And it's done.

Hope it's still useful :D

**Comment by TerraZ-UO** [comment]
Hey @Minibus93, thanks for the info. Actually, it was me who commented 😅. 

I deleted the comment because I was able to fix it myself (well, sort of). I found some css related to the container indicator in the userChrome.css and deleted them. But, your solution is much better. I can't thank you enough for the deatiled response and sorry for causing the confusion.
