### ISSUE TITLE
Minimize Maximimize hover have normal fallback style 

### ISSUE THREAD

**Issue by Raptor0007** [QNetITQ/WaveFox#137]
The theme is perfectly fine but it has only above issue 
<img width="758" alt="Screenshot 2023-05-11 102336" src="https://github.com/QNetITQ/WaveFox/assets/119287176/9318697f-2eaa-46b2-a2f8-38d604b4b174">
<img width="783" alt="Screenshot 2023-05-11 102416" src="https://github.com/QNetITQ/WaveFox/assets/119287176/96f9f121-3467-4ffb-b551-5d39a91aa62b">

**Comment by QNetITQ** [comment]
Many people have already told me about this. I don't know yet how to solve it. I'll think of something, but a little later.

**Comment by Deathbyteacup** [comment]
Already solved in this pull request: https://github.com/QNetITQ/WaveFox/pull/122

**Comment by QNetITQ** [comment]
This is not the finished version. Some things will need to be corrected.

**Comment by Raptor0007** [comment]
Thanx @QNetITQ Now it is working fine .You fixed that 
<img width="795" alt="Screenshot 2023-05-13 151135" src="https://github.com/QNetITQ/WaveFox/assets/119287176/57db1cce-3fbe-4885-a8ff-8ae197786f9e">
