### ISSUE TITLE
Playing/Mute icon is different ... moves down one line

### ISSUE THREAD

**Issue by privacyguy123** [QNetITQ/WaveFox#138]
Any way to change this back to the default?

![image](https://github.com/QNetITQ/WaveFox/assets/50337995/db26215f-3e5b-49e7-80df-bcf568b49c18)

**Comment by QNetITQ** [comment]
Delete everything in this [section](https://github.com/QNetITQ/WaveFox/blob/8ab846cbb15e8655f035c01a7508d6bc9fb508c3/chrome/userChrome.css#L869)

**Comment by privacyguy123** [comment]
Cheers mate! Keep  up the good work. Awesome theme for MaterialFox refugees.
