### ISSUE TITLE
Hide tab separator on first tab

### ISSUE THREAD

**Issue by privacyguy123** [QNetITQ/WaveFox#139]
I don't think we need one to the left of the first tab

**Comment by QNetITQ** [comment]
This separator is only present if there is something before the tabs. I can remove it entirely, but I'll have to think about it.

**Comment by privacyguy123** [comment]
for me it is showing left of first tab :S

**Comment by privacyguy123** [comment]
nothing

![image](https://github.com/QNetITQ/WaveFox/assets/50337995/751bb23c-c54e-4ef7-a499-a3119b070dc4)

**Comment by QNetITQ** [comment]
If you are using the current version of the style, then this is strange. I have everything working as intended. In general, okay. I will remove this separator. It does not perform important functions.

**Comment by QNetITQ** [comment]
Look like that's it. I've made a few more changes to how separators work

**Comment by privacyguy123** [comment]
These are appearing back between every tab, even pinned ones to far left - seems uncessary to have this seperators show. Is it possible to hide in between pinned tabs at least?

**Comment by QNetITQ** [comment]
Do you want to leave separators only for regular tabs?

**Comment by QNetITQ** [comment]
@privacyguy123 You can now remove pinned tab separators. Go to the discussion section. It says there how to do it.
