### ISSUE TITLE
Add an option to have title bar container disabled within the mica/acrylic mode

### ISSUE THREAD

**Issue by Patricek0056** [QNetITQ/WaveFox#147]
Hello, I have Firefox without title bar container, because I have MinMaxClose button from Firefox Scripts by xiaoxiaoflood, but if I've applied the `windows_11_10.css` then there already are title bar container buttons, which I don't like. So I want an option in `about:config` which would disable the title bar container (minimize, maximize, close buttons) with enabled mica/acrylic mode within the `windows_11_10.css`.

Thank you for understanding my issue!

Oh, and if you implement it, then tell me how is that option named.

**Comment by Patricek0056** [comment]
Sorry, that I changed the title too often, but the title is now completed.

**Comment by QNetITQ** [comment]
I don't support third party styles or modifications so I won't make a separate key for that. But if you just need to disable the window control buttons, just use the code below. It doesn't disable the buttons, it hides them.

<code>
.titlebar-buttonbox-container
{
    pointer-events: none !important;
    /* or */
    z-index: -1 !important;
}
</code>

**Comment by Patricek0056** [comment]
No! This issue is unrelated to xiaoxiaoflood's MinMaxClose, I only said, that I have it installed.

**Comment by Patricek0056** [comment]
Also, I added this code to `windows_11_10.css` and nothing have changed.

**Comment by Patricek0056** [comment]
I must remove `windows_11_10.css` from my userChrome.css, because it causes problems with status bar.

**Comment by QNetITQ** [comment]
My code disables window control buttons. I thought you were talking about it. Can you clarify what you want to do? Preferably with screenshots.

**Comment by QNetITQ** [comment]
I read your message again. If you need to disable not the window control buttons, but the block in which they are located, then the code below should handle this.

```
.titlebar-buttonbox-container
{
    display: none !important;
}
```
Add this code [here](https://github.com/QNetITQ/WaveFox/blob/2161f018896867522de1ddac7d213f819d17952e/chrome/special/windows_11_10.css#L59). You can delete lines from [61](https://github.com/QNetITQ/WaveFox/blob/2161f018896867522de1ddac7d213f819d17952e/chrome/special/windows_11_10.css#L61) to [135](https://github.com/QNetITQ/WaveFox/blob/2161f018896867522de1ddac7d213f819d17952e/chrome/special/windows_11_10.css#L135).
