### ISSUE TITLE
No transparency

### ISSUE THREAD

**Issue by AIP21** [QNetITQ/WaveFox#149]
My transparency effects have stopped working and now the titlebar is just an opaque light gray.

I noticed you removed the transparency effects options from the readme, is this option no longer supported by firefox?

**Comment by QNetITQ** [comment]
Starting with Firefox 117, transparency is not supported by the browser. Therefore, I removed the code associated with it, since it is no longer relevant. Use Firefox 115 ESR. Everything will work there for at least another 15 months.

**Comment by AIP21** [comment]
Got it, thank you.
