### ISSUE TITLE
What happened to shadows?

### ISSUE THREAD

**Issue by K4sum1** [QNetITQ/WaveFox#150]
I upgraded from 102 to 115, and tab shadows are gone. I tried to add them to the 115 css, but the code just doesn't work. The shadows did work in 115 ESR with the old theme, so it should be an easy fix.

**Comment by QNetITQ** [comment]
Since the release of the style for version 102, I have changed the keys responsible for the shadows. Just adjust the shadows again.

**Comment by K4sum1** [comment]
I tried enabling these two and I don't see any difference (In Waterfox G6 beta)
    userChrome.DarkTheme.TabFrameType.Border.Enabled
    userChrome.DarkTheme.TabFrameType.Shadow.Enabled

**Comment by QNetITQ** [comment]
It doesn't work like that. In the description of this option it is written from what the shadow is formed.

**Comment by K4sum1** [comment]
Ah, I'm dumb. How come all the about:config things are changed?

**Comment by QNetITQ** [comment]
I don't remember myself. See for yourself.
