### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by K4sum1** [QNetITQ/WaveFox#151]
I have this fork of Firefox source, and it runs under 7. There are a couple issues currently though. (One might be something someone like you that knows CSS might be able to help with)
https://github.com/Eclipse-Community/gecko-dev-win7

Since this exists (and there will probably be more forks when 116 or 117 releases), might be a good idea to restore 7 support.

**Comment by QNetITQ** [comment]
From version 117 of the browser, the code responsible for the old operating systems has already been removed. Even if you can bypass the check for the version of Windows you are using, nothing will work anymore. Style for 115 ESR supports older systems and is the most functional. Even more functional than the release.

**Comment by K4sum1** [comment]
https://github.com/Eclipse-Community/gecko-dev-win7/issues/3
"Mozilla removed most of the code for styling for 7/8, this will likely need to be selectively reverted to not break future changes."

**Comment by QNetITQ** [comment]
And who will return it? And most importantly, how? I only know web technologies well (HTML/CSS/JS/XML). I know C++ and Rust at a very basic level.

**Comment by K4sum1** [comment]
I might dive into it, however for 117 when the changes hit it might just be a basic bandaid revert on my part. Maybe Superfox when it exists will do something better.

95% of the changes are in CSS. So I think you could realistically do it. I edited the issue to add more commits that I had found and forgot to add.

**Comment by QNetITQ** [comment]
For now, I'll close this issue. If you decide something with the removed code from new versions of the browser, open it again.

**Comment by RibShark** [comment]
Seconding this, I'm using this fork on Windows 11 and would like the ability to re-enable the titlebar blur with this version!

**Comment by QNetITQ** [comment]
@K4sum1 @RibShark
 
Mozilla is already working on supporting transparency on Windows. Perhaps in June/July the browser will support it out of the box. Until then, I can return transparency to this fork, but only for Windows 11/10.
