### ISSUE TITLE
Method to adjust Container Indicators background-color color-mix

### ISSUE THREAD

**Issue by kyleung271** [QNetITQ/WaveFox#154]
Would it be possible to have option for background-color color-mix in Container Indicators?
The color mix work not as well when there are tab overlaps (e.g. tab option 12)

Currently the following section is commented out to turn off the Container Indicators background-color color-mix:
```
/*
.tabbrowser-tab[usercontextid] .tab-background
{
    background-color: color-mix(in srgb, var(--identity-icon-color) 25%, transparent);
}
*/
```

**Comment by QNetITQ** [comment]
All is ready. Don't use the new style version right now. Wait until the browser is updated to version 117
