### ISSUE TITLE
Sides of each tab is black since new update (version 117)

### ISSUE THREAD

**Issue by Xeway** [QNetITQ/WaveFox#155]
I'm on Firefox Developer Edition with version 117.0b4.

Here's how tabs look like:

![Screenshot of the tabs](https://github.com/QNetITQ/WaveFox/assets/65366494/957f2de8-63c8-47ae-baf1-30e91d0e299e)

**Comment by QNetITQ** [comment]
Use the style in 1.6.117 beta. I don’t know what other changes I will make before the release, but in general, it is ready.

**Comment by Xeway** [comment]
Ok thanks, I prefer to wait for the "stable" release for now. Do you know when will it be released?

**Comment by QNetITQ** [comment]
This time it will be August 20 - 22.

**Comment by QNetITQ** [comment]
All is ready. Don't use the new style version right now. Wait until the browser is updated to version 117

**Comment by Xeway** [comment]
Hey, thanks for your reminder. I'm already using 117 because I have Developer Edition :)
