### ISSUE TITLE
CSS theme doesn't seem to work properly on Firefox 116???

### ISSUE THREAD

**Issue by Harleythetech** [QNetITQ/WaveFox#156]
Here's an image of what is happening when i use the css you provided, i did apply the following in about config and set the boolean to true:
```
toolkit.legacyUserProfileCustomizations.stylesheets =>true
layout.css.has-selector.enabled =>true
svg.context-properties.content.enabled =>true
userChrome.Tabs.Option4.Enabled =>true
userChrome.DarkTheme.TabFrameType.Border.Enabled =>true
userChrome.DarkTheme.TabFrameType.Shadow.Enabled =>true
userChrome.DarkTheme.TabFrameColor.Black.Enabled =>true
userChrome.DarkTheme.TabFrameSaturation.Medium.Enabled =>true
```

Firefox Version: 116.0.2
OS: Windows 11 22H2 Insider Build
### **Proof:**
toolkit.legacyUserProfileCustomizations.stylesheets =>true
![image](https://github.com/QNetITQ/WaveFox/assets/51787264/ff94bcd3-f91a-4928-9c93-97e0ec8c9dbc)
toolkit.legacyUserProfileCustomizations.stylesheets =>false
![image](https://github.com/QNetITQ/WaveFox/assets/51787264/5f9d6efd-403b-4fa2-99e3-98e5f2977af1)

**Comment by Harleythetech** [comment]
idk if this helps but i stored the chrome files here:
![image](https://github.com/QNetITQ/WaveFox/assets/51787264/5975400f-b36b-4d8f-a9e6-7f5bac4e435f)

**Comment by QNetITQ** [comment]
You must have installed the v1.6.117 Beta style. It uses completely new CSS properties. Therefore, it does not work on Firefox 116 and below. Download the style from the releases section.

**Comment by QziP22** [comment]
> Are you using v1.6.117 Beta? If yes, then replace it with the release one (v1.6.116) or activate the `layout.css.nesting.enabled` key. However, I do not know how it is implemented in the 116 version of the browser.

I was having the same problem but this solved it. Thank you!

**Comment by Harleythetech** [comment]
> Are you using v1.6.117 Beta? If yes, then replace it with the release one (v1.6.116) or activate the `layout.css.nesting.enabled` key. However, I do not know how it is implemented in the 116 version of the browser.


Activating `layout.css.nesting.enabled` worked for me! Thanks for the help!
