### ISSUE TITLE
"Extending" the new tab button

### ISSUE THREAD

**Issue by edo0** [QNetITQ/WaveFox#16]
First of all, thank you very much for all your work, on WaveFox, it is an amazing CSS for Firefox, and a breath of fresh air from their current design policies.

I wanted to ask you if there was a way to "extend" the New Tab button, so that also the concavity of the slope of the easternmost Australis tab were to trigger the opening of a new tab — or, in other words, reduce the dead space between the "close tab" and "new tab" buttons in the Australis theme.  
Thank you in advance for looking into this!!

**Comment by QNetITQ** [comment]
Hello. This distance was introduced to address tab behavior issues and to be symmetrical with other buttons.

I can try to make this button as in the 29 - 56 versions of the browser, but first I need to study the available methods and the negative consequences. Only then will I be able to say more precisely.

**Comment by edo0** [comment]
Thank you very much, that would be great!

**Comment by QNetITQ** [comment]
Early implementation
![изображение](https://user-images.githubusercontent.com/85301851/149181878-ed42a57d-fb9e-45f0-bf3c-cf8ca8f2fbe9.png)

**Comment by QNetITQ** [comment]
In general, everything is ready. It remains only to format the code. I'll post today or tomorrow.

**Comment by edo0** [comment]
Thank you very much!!

**Comment by QNetITQ** [comment]
Added as an option.

**Comment by edo0** [comment]
Works perfectly, thank you again!
