### ISSUE TITLE
There is no separator after the last tab before the new tab button

### ISSUE THREAD

**Issue by dreamsynth** [QNetITQ/WaveFox#165]
Is it possible to somehow add this separator?

**Comment by QNetITQ** [comment]
This separator is missing for a reason. It does not work everywhere it should and it is currently impossible to change this. I can only return the first and last separator in Firefox 120, but not in 118 and 119.

**Comment by QNetITQ** [comment]
Edge separators have been added. But you need Firefox 120. It will not work on earlier versions, or will work with errors.
