### ISSUE TITLE
No transparency when window not focused

### ISSUE THREAD

**Issue by Yasso9** [QNetITQ/WaveFox#166]
When my Firefox window is not focused, there is no transparency anymore. I have set the `userChrome.Linux.Transparency.High.Enabled` and `userChrome.Toolbar.Transparency.Medium.Enabled` in about:config

**Comment by QNetITQ** [comment]
Do you find this behavior undesirable?

**Comment by Yasso9** [comment]
Unfortunately yes, is there a way to allow a window to still have the transparency even if the window is not focused. By changing the CSS or anything ?

**Comment by QNetITQ** [comment]
In [this line](https://github.com/QNetITQ/WaveFox/blob/980018178da5b8a351a43ededd7ec617f5aade76/chrome/special/linux.css#L37C61-L37C61) you need to remove `, :-moz-window-inactive`

**Comment by Yasso9** [comment]
Thanks a lot ! It works pretty well now.
By the way awesome theme
