### ISSUE TITLE
Adding a certain line in userChrome removes the background highlight from the tab you're currently on.

### ISSUE THREAD

**Issue by metronightly** [QNetITQ/WaveFox#168]
Sorry if this is not related to wavefox itself, but I don't know where else to ask about it.

I am currently using the latest wavefox in firefox 119 with the only change in the userChrome.css being the addition of this line:
`.titlebar-close           {display:none !important;}`

Upon adding this line to your userChrome.css, you will notice that firefox will no longer highlight the tab you're in

This is Firefox with the above line and as you can see, I'm on the settings page but it's not highlighted.
![image](https://github.com/QNetITQ/WaveFox/assets/75716685/bb51eefc-7255-4c35-b743-8319dc184805)

Now this is on the same profile without that particular line: 
![image](https://github.com/QNetITQ/WaveFox/assets/75716685/2f324f1d-3023-4033-bf90-406b40133424)

Could this be fixed somehow?

**Comment by QNetITQ** [comment]
The background of the active tab and the property you are trying to add are not related in any way. Add your property to the very bottom of the [windows.css](https://github.com/QNetITQ/WaveFox/blob/v1.6.119/chrome/special/windows.css) file, behind all the brackets.

**Comment by metronightly** [comment]
> Add your property to the very bottom of the [windows.css](https://github.com/QNetITQ/WaveFox/blob/v1.6.119/chrome/special/windows.css) file, behind all the brackets.

Wow, huge thanks, that worked perfectly. So basically I shouldn't touch userChrome.css but instead try things on the windows.css file from now on. Thank you again.

**Comment by metronightly** [comment]
Btw did you make any changes to the List all tabs button in the recent wavefox update? Previously it was round shape (like the present open a new tab button) but now list it has the default firefox look (rectangular with curved edges)

**Comment by QNetITQ** [comment]
Yes. I removed the curves from some elements. Temporary or not, I don’t know yet.

**Comment by metronightly** [comment]
Thanks, love your work 🔥
