### ISSUE TITLE
Accent color (Win11)

### ISSUE THREAD

**Issue by kocane** [QNetITQ/WaveFox#17]
Sorry if I'm missing something obvious but in the latest version (I was quite a few versions behind before) I can't seem to make my accent color work. My titlebar area is just the stock grey. Do I need to set something somewhere?

**Comment by QNetITQ** [comment]
Hello. The accent color is still available and tied to the browser's system theme. Try deleting the chrome folder and copying the downloaded folder with all its contents.

**Comment by kocane** [comment]
You're right. No sure what I was doing wrong. Thanks!

**Comment by kocane** [comment]
@QNetITQ Has something changed with the later version? My accent color is no longer used in the firefox titlebar.

Noted should be that the last version I had still used "style" instead of "userchrome" in about:config. I've adjusted my config to the new name standard. I've tried deleting the Chrome folder and copying over all the files from the lastest version.

![image](https://user-images.githubusercontent.com/7694813/177978774-d37bba8d-b1c4-4029-b5dd-4c7f6215dcfb.png)

**Comment by QNetITQ** [comment]
Accent color changed for Firefox 103+. For Firefox 102, you need to activate compatibility with ESR.

**Comment by kocane** [comment]
@QNetITQ My FFX finally got upgraded to 103, so I upgraded WaveFox as well.

It's odd though, the accent color seem to be the one that I use for inactive window borders (set in registry manually) and not the accent color I selected in Windows settings, like it was pre-103.

Example from Explorer:
![image](https://user-images.githubusercontent.com/7694813/181359169-f7f6f748-7688-4a2e-8b85-a6d9ccb9c1f7.png)

and here is how it looks in Firefox
![image](https://user-images.githubusercontent.com/7694813/181359253-3014d53f-f980-49c6-ba46-dbeb320723ab.png)

Obviously the regedit tweak I have made in order to have a specific color on inactive titlebars is not exactly supported but it didn't use to be an issue and I wonder where Firefox/Wavefox gets it from?

**Comment by QNetITQ** [comment]
I also noticed this change from version 103. Now the accent color behaves like with uvp applications, you can't set the color too bright or too dark. Probably the key in the registry with the color value was changed to another.

**Comment by kocane** [comment]
@QNetITQ Very weird.

Anyway, since I already use custom code (which I of course disabled before reporting this 'bug') to change the inactive titlebar color in Firefox, since it doesn't respect the one in set in registry, I just used the same code to change the active titlebar color to what I wanted.
```
:root[tabsintitlebar]:is(:not(:-moz-lwtheme), [lwt-default-theme-in-dark-mode]):is(:-moz-window-inactive) .titlebar-color
{
    background-color: #404040 !important;
    color: white !important;
}

:root[tabsintitlebar]:is(:not(:-moz-lwtheme), [lwt-default-theme-in-dark-mode]) .titlebar-color
{
    background-color: #242424 !important;
    color: white !important;
}
```
S'all good, man.

By the way, the one-line style you're experimenting with is a hella cool idea. Shame I love the Australis tabs so much.
