### ISSUE TITLE
Tab separators and menu icons won't show up

### ISSUE THREAD

**Issue by Terepin** [QNetITQ/WaveFox#170]
And I don't understand why. They were working in Firefox 118 just fine, but not in 119. Everything is enabled as it should and I tried it even on clean profile, but still nothing.
![obrázok](https://github.com/QNetITQ/WaveFox/assets/9349868/7efcd691-74b4-4075-88b7-cc8c3d4e86a5)

**Comment by QNetITQ** [comment]
I see. You are using keys for v1.6.120. On the main page there is a link for version 1.6.119. There is also a link in the releases section.

**Comment by Terepin** [comment]
Ah, now it works. :) Thanks. I didn't realize the keys changed.

While I am here, can I have a small request? Would it be possible to add missing icons?

**Comment by QNetITQ** [comment]
What icons are you talking about?

**Comment by Terepin** [comment]
For example, "More Tools" and "Exit" in main menu don't have icons. Also plenty of options in contextual menu don't have icons. I saw other CSS theme that had them all (or almost all). Would be nice to have them here as well.

**Comment by QNetITQ** [comment]
I added icons similar to Microsoft Edge.

<b>IMO</b>
I can fill everything with icons, but the question is - why? Only the most frequently used menu items should have icons. Only then will it work as intended. Authors who fill everything they can with icons do not think about user convenience, but only create the appearance of a lot of work done and try to increase their value in the eyes of others. Most of them, as a rule, accept donations.
