### ISSUE TITLE
Add 'Close button on hover' key / switch

### ISSUE THREAD

**Issue by dcog989** [QNetITQ/WaveFox#172]
Feature request: Add 'Close button on hover' key / switch. Optionally have separate switches for active and inactive tabs.

I've implemented it for now by adding to _third_party_custom_styles.css_ the following:

```
.tabbrowser-tab:not([pinned]) .tab-close-button {
  display: none !important
}
.tabbrowser-tab:not([pinned]):hover .tab-close-button {
  display: inline-flex !important
}
```

P.S. I've just installed WaveFox - very impressed by the elegant coding / implementation. Very nice!! :)

**Comment by QNetITQ** [comment]
That's why I'm going to add the ability to implement third-party styles from the next release. The style already supports everything that is most in demand. The rest you can add yourself. I've updated the description and made some links available.

**Comment by dcog989** [comment]
OK. I just thought this feature would be popular enough with users to include as one of the built-in settings.
