### ISSUE TITLE
Excessive left / right padding on tab bar?

### ISSUE THREAD

**Issue by dcog989** [QNetITQ/WaveFox#173]
![WaveFox tab bar padding](https://i.imgur.com/m5ppPsg.png)

The padding to left of tabs when window is not maximized appears excessive. Could it be reduced? Note - when the window is maximized then padding is OK.

The padding to right of _List All Tabs_ appears excessive. Could this be reduced? Perhaps match the padding between the right tab and the '+' new tab button?

**Comment by QNetITQ** [comment]
This is the default behavior. Disabled using the `userChrome.DragSpace.Left.Disabled` and `userChrome.DragSpace.Right.Disabled` keys.

**Comment by dcog989** [comment]
I understand now. Thanks.
