### ISSUE TITLE
Tab Styles Not Applied

### ISSUE THREAD

**Issue by dividedby** [QNetITQ/WaveFox#176]
I am not sure if this is an issue or not but none of the tab styles are applying, see the screenshot attached.

Firefox 119.0.1
`userChrome.Tabs.Option8.Enabled`
`userChrome.TabSeparators.Saturation.Low.Enabled`
`userChrome.LightTheme.Tabs.Borders.Enabled`
`userChrome.LightTheme.Tabs.Shadows.Saturation.Low.Enabled`

![issue](https://github.com/QNetITQ/WaveFox/assets/64715420/69892f38-25d0-4fa4-bb54-73d2acb53ac5)

**Comment by QNetITQ** [comment]
![изображение](https://github.com/QNetITQ/WaveFox/assets/85301851/a77ee06c-44ea-4e5b-ac7d-e37162ee20b3)
Check the browser version and stylesheet version match. The keys for each version may differ. Follow the link (if you do not have a 120 version of browser and style) and check out the list of available options.

**Comment by dividedby** [comment]
Ahh, thanks and sorry about raising an issue then! I deleted the Chrome folder and reinstalled with the 1.6.119 download, re did the keys, and it is working again. I am wondering, in your opinion, what keys would you say most closely replicate Chrome's current design?

`userChrome.Tabs.Option8.Enabled`
`userChrome.TabSeparatorsMediumSaturation-Enabled`

Any of the Tab Frame keys or anything else that would bring it in line with Chrome?

**Comment by QNetITQ** [comment]
This style cannot even come close to being called a replication of Google Chrome or any of the known design languages. This is the usual Mozilla Proton UI, with some changes, so I can’t give you any advice here.
