### ISSUE TITLE
Tab title misalignment

### ISSUE THREAD

**Issue by akumei0** [QNetITQ/WaveFox#18]
Just installed but the tab titles seem to be misaligned, like they're slightly higher than they should be. I'm on macOS 11.

![wavefox](https://user-images.githubusercontent.com/98200672/151631376-7fc3ade7-7ffd-485b-9232-bd98ea1a7be5.png)

**Comment by QNetITQ** [comment]
Mozilla have made changes to the font markup since 96.0.2. The style is designed for 96.0.2 and newer. On 96.0.1 and below, this bug appears. At the moment I can't support the ESR branch. Maybe in the future.

**Comment by akumei0** [comment]
Updated and you were right—it's now fixed!
