### ISSUE TITLE
Selected Tab Indicator not working

### ISSUE THREAD

**Issue by trbatukim** [QNetITQ/WaveFox#184]
Selected tab indicator not working on Firefox 121 + WaveFox v1.6.121 even though userChrome.Tabs.SelectedTabIndicator.Enabled key is set to true
![resim](https://github.com/QNetITQ/WaveFox/assets/99345193/861b3479-795a-4531-9e89-1219d97d9be0)

**Comment by QNetITQ** [comment]
Yes, there was such a bug in v1.6.120. At first it was in v1.6.121, but a couple of days ago [I fixed it](https://github.com/QNetITQ/WaveFox/commit/b4ddefc4e2bfccd7f809eca2b819e9a95ffbf2c2). Try reinstalling the style.

**Comment by trbatukim** [comment]
Yep, updating the style fixed the issue. Thanks!
