### ISSUE TITLE
Can't be installed

### ISSUE THREAD

**Issue by Hazzy12345** [QNetITQ/WaveFox#19]
I followed the installation guide and nothing happened. I may just have the folder in the wrong directory. It specified "root" folder so I tried my C: drive. Nothing happened. It said this is also known as "user folder" so I tried C:/Users/my username. Nothing happened.

**Comment by Sarptra** [comment]
Your user profile root folder go about:profiles and open root folder

**Comment by QNetITQ** [comment]
This refers to the browser user profile folder. I'll update the instructions so this question doesn't come up again.

**Comment by Hazzy12345** [comment]
This really helped, thanks!

**Comment by QNetITQ** [comment]
As far as I understand the problem is solved. Then I will close the bug report.

**Comment by dddictionary** [comment]
i have a similar issue. on linux, I navigate to `~/.mozilla/firefox/<some_text.default>` and then put the chrome folder inside there. when i reload firefox, the `userChrome` field in `about:config` does not show up. 

for more context, I put the chrome folder in both of these directories:
![image](https://user-images.githubusercontent.com/86024593/230667366-f0ab4a75-15ce-4a0c-838c-d5c56274fc26.png)

**Comment by QNetITQ** [comment]
The keys themselves will not appear. They must be created. I wrote everything in detail in the instructions. Use release v1.5.111.
