### ISSUE TITLE
Transparency not working when unfocused

### ISSUE THREAD

**Issue by Gxnum** [QNetITQ/WaveFox#191]
It works fine while I am using Firefox, but when I open another window and switch to that, Firefox's transparent top bar becomes opaque white, and opaque black when dark mode.

![image](https://github.com/QNetITQ/WaveFox/assets/65645307/9ff123d8-82be-4dd5-9f94-7b747cb4f965)

![image](https://github.com/QNetITQ/WaveFox/assets/65645307/e981eeb0-5538-4317-bf3c-ba5ab52899e0)

**Comment by QNetITQ** [comment]
This just helps to understand whether the window is active or not. I can remove this effect if you want.

**Comment by Gxnum** [comment]
> This just helps to understand whether the window is active or not. I can remove this effect if you want.

Yea I'd love to, thanks. I am not really good at css.

**Comment by Gxnum** [comment]
Also how do I change the color of the top bar?

**Comment by QNetITQ** [comment]
Made changes. In the next release, an inactive window will remain transparent.

The system itself sets the color of the tab bar. If your Linux distribution allows you to control the color of the title bars, then simply change it in the settings. If this is not possible, you will have to specify the color manually, but in the style.

**Comment by Gxnum** [comment]
Tysm, lmk when the next release will happen!

**Comment by QNetITQ** [comment]
https://github.com/QNetITQ/WaveFox/releases/tag/v1.6.123

**Comment by Gxnum** [comment]
> https://github.com/QNetITQ/WaveFox/releases/tag/v1.6.123

Thank you so much, it works great!
