### ISSUE TITLE
[Question] Will this theme work with Floorp Browser?

### ISSUE THREAD

**Issue by thohnb** [QNetITQ/WaveFox#194]
Hi @QNetITQ ! 

First of all ! I find interesting theme when i saw on randomly on Internet. 
Since im using Floorp Browser, i wonder this theme will work with this browser?

Also will you update the theme of ESR version when Firefox updated in future?

Thanks you!

**Comment by QNetITQ** [comment]
Floorp uses Firefox 115 ESR, so in theory it should work.

ESR style is updated only if there are problems. Fortunately, as a rule, there are none.

When Firefox 128 ESR comes out I will update the style for it.
