### ISSUE TITLE
Adjusting the width of userChrome.DragSpace.Top.Maximized.Enabled

### ISSUE THREAD

**Issue by wealstarr** [QNetITQ/WaveFox#196]
Hello,

Thank you for this work, absolutely amazing. Thank you for providing so many options, that makes this project stands out from the rest.

I enabled the top drag space but it's too wide for my liking, I just want enough for the border (already enabled) to be visible. Is there any way to adjust the width of the top drag space ?

Any help will be greatly appreciated.

**Comment by QNetITQ** [comment]
Create a file to add third-party styles and paste the code below

```
:root
{
    --drag-space: 4px !important;
}
```

**Comment by wealstarrr** [comment]
> Create a file to add third-party styles and paste the code below
> 
> ```
> :root
> {
>     --drag-space: 4px !important;
> }
> ```

Thank you for the response. Your help is highly appreciated.
