### ISSUE TITLE
Tab border color doesn't change when installing custom themes

### ISSUE THREAD

**Issue by dreamsynth** [QNetITQ/WaveFox#197]
Even though the custom theme has a yellow tab border color, the tab border color does not change when the theme is applied.

| How it should be | How it appears |
| --- | --- |
| ![изображение](https://github.com/QNetITQ/WaveFox/assets/84819091/ac24f280-ca64-4f71-82b5-387c9791fcee) | ![изображение](https://github.com/QNetITQ/WaveFox/assets/84819091/28e874ce-0fcc-48d5-a520-c08db492d20b) |

Firefox Dev 127.0b3
``userChrome.Style.ThirdParty.Enabled``
``userChrome.Tabs.Option2.Enabled``
``userChrome.LightTheme.Tabs.Borders.Enabled``
``userChrome.DarkTheme.Tabs.Borders.Enabled``

**Comment by QNetITQ** [comment]
I'm going to change the way tab borders are handled in v1.6.127. The old method is quite complicated, inflexible and does not work with translucent surfaces. This can be bypassed, but then there will be problems with compatibility with some themes from AMO. Just enable the key `userChrome.Tabs.SelectedTabIndicator.Enabled`.

**Comment by dreamsynth** [comment]
Could you please tell if in the future it will be possible to show the selected tab indicator as a border like in the original Firefox theme?

**Comment by QNetITQ** [comment]
This is not easy to do and will require a lot of compromises. Most likely I won't even try.

**Comment by QNetITQ** [comment]
I made shadows compatible with AMO themes. As much as possible, given the limitations. Should work starting with v1.7.131.
