### ISSUE TITLE
Transparency on Linux (Firefox 127 and newer)

### ISSUE THREAD

**Issue by QNetITQ** [QNetITQ/WaveFox#199]
Judging by my observations, Firefox 127 no longer requires a key `gfx.webrender.all` for transparency to work with both X11 and Wayland. Need more information.

**Comment by Not-A-Coder2023** [comment]
I think the newest version of WaveFox broke the close tabs to the left/right text in the Midori browser. I'm using the latest Windows build because for some reason installing the FF 115ESR version didn't really work

**Comment by QNetITQ** [comment]
I don't check how the style works on forks. Midori uses third-party styles by default. For my style to work correctly, I need to switch to using the original theme from Mozilla.
