### ISSUE TITLE
What settings are required for the "shadow-like border"?

### ISSUE THREAD

**Issue by akumei0** [QNetITQ/WaveFox#20]
What settings are required to get the tab shadow to look like the middle screenshot? I've looked through the userChrome.css settings, but can't seem to find it.

![shadowlikeborder](https://user-images.githubusercontent.com/98200672/151686631-cccec9d8-73ee-4ad6-bd95-b1fd2804d29c.png)

**Comment by QNetITQ** [comment]
https://github.com/QNetITQ/WaveFox/blob/f66366e8e25c5d8c8bf0937e64ea3fcca308a0fe/chrome/userChrome.css#L21
I'll probably put everything in optional keys. This is easier for most users.

**Comment by akumei0** [comment]
Hm. I have those same settings but it ends up looking like the 3rd screenshot. I'll just wait for if/when you make those optional keys available.

**Comment by QNetITQ** [comment]
Okay. I'll post it in the next two days.

**Comment by QNetITQ** [comment]
Ready. I haven't taken screenshots yet, but you can already set it up
