### ISSUE TITLE
No blur in KDE

### ISSUE THREAD

**Issue by twisty-nado** [QNetITQ/WaveFox#202]
The title explains it.
![image](https://github.com/user-attachments/assets/8ffe3c73-c7e4-4eb9-87f6-2e60d6c0fa2d)

**Comment by QNetITQ** [comment]
To blur the background you need to install an add-on in the system.
https://github.com/esjeon/kwin-forceblur or https://github.com/taj-ny/kwin-effects-forceblur

**Comment by twisty-nado** [comment]
put that in your project's info page or something lol
