### ISSUE TITLE
Help removing window buttons + Blur

### ISSUE THREAD

**Issue by soyelmismo** [QNetITQ/WaveFox#204]
when i have the window maximized, i have the window buttons in my panel automatically, but i only can have blur with wavefox when `browser.tabs.inTitlebar` is 1...
![imagen](https://github.com/user-attachments/assets/17a98dd1-f6f6-448a-8cce-58d01b5df652)

i want to disable these firefox window buttons and at the same time (if possible) have it with the beauuutiful blur 🥴 
![imagen](https://github.com/user-attachments/assets/e9c9e78f-9b15-4e51-9788-116c838d14e8)

im running it with Plasma 6 and kwin forceblur

**Comment by QNetITQ** [comment]
I did not change the behavior of the window control buttons in Linux. They behave as Mozilla intended. It may be possible to do something about this, but a little later. The style is configured in such a way that the blur is displayed only if the tabs are in the title bar. If the system title bar is active, the blur does not work. I can fix this, but only in version 130 of the style.

For Plasma 6 it is better to use a more recent script
https://github.com/taj-ny/kwin-effects-forceblur

**Comment by soyelmismo** [comment]
> https://github.com/taj-ny/kwin-effects-forceblur

yes, im using it

![imagen](https://github.com/user-attachments/assets/f876b1bd-e7c1-4cb9-89d2-444f1ee1ca4e)

**Comment by QNetITQ** [comment]
Transparency now works even when the tab title bar is active.

**Comment by QNetITQ** [comment]
The code below should remove the window control buttons when the window is maximized. Add it as third-party code. See FAQ.

```
:root[sizemode="maximized"] .titlebar-buttonbox-container
{
    display: none !important;
}
```
