### ISSUE TITLE
Missing drop indicator in the tab bar

### ISSUE THREAD

**Issue by dreamsynth** [QNetITQ/WaveFox#207]
I noticed that there is no drop indicator in the tab bar when using this CSS theme.

| How it appears | How it should be |
| --- | --- |
| ![How it appears](https://github.com/user-attachments/assets/c57697f5-c2d3-496c-b1d9-1749498b2101) | ![How it should be](https://github.com/user-attachments/assets/59e1fdd7-ad72-42f6-a077-3c50a052153b) |

I used this CSS code to fix this problem:

``` css
.tab-drop-indicator {
  z-index: 999 !important;
  opacity: 1 !important;
}
```
However, I would like to clarify, is there any reason why this was done?

Firefox Dev 131.0b3
`userChrome.Tabs.Option2.Enabled`
`userChrome.LightTheme.Tabs.Shadows.Blur.Low.Enabled`
`userChrome.LightTheme.Tabs.Shadows.Saturation.High.Enabled`
`userChrome.DarkTheme.Tabs.Shadows.Blur.Low.Enabled`
`userChrome.DarkTheme.Tabs.Shadows.Saturation.High.Enabled`
`userChrome.DragSpace.Left.Disabled`

**Comment by QNetITQ** [comment]
This indicator is hidden on purpose. I use a rather non-obvious system to make the tab scroll animation work in overflow mode. In this mode, this indicator is not displayed correctly. The last time I tried, I couldn't get it to align, so I just hid it. I'll try again to make it display correctly, but I can't promise that it will work.

**Comment by QNetITQ** [comment]
The layout of pinned tabs is expected to change soon. After that, I will most likely be able to make the indicator work for all modes without exception.

https://bugzilla.mozilla.org/show_bug.cgi?id=1910097
