### ISSUE TITLE
Tab selection overlays selected tab with theme 11

### ISSUE THREAD

**Issue by CDanilo25** [QNetITQ/WaveFox#208]
With the option n.11 for the tab layout, the "hover" color of a unselected tab overlays the color for the selected tab, if the selected tab is at the immediate left of the hover color, as showed below.
![selected tab issue](https://github.com/user-attachments/assets/16e598a3-a1d9-4010-a14c-744cfc98cfde)

The issue is not present in other contexts.
![immagine](https://github.com/user-attachments/assets/c892d17a-d42c-4f6f-be55-da20706e9df6)
![immagine](https://github.com/user-attachments/assets/e77649de-5213-4b28-ae01-6b1941f2165f)

Selected options:

- All the options dedicated to the Lepton Icons.
- `userChrome.Tabs.Option11.Enabled`
- `userChrome.WaveFoxTabs-Enabled`
- `browser.theme.windows.accent-color-in-tabs.enabled`

WaveFox v.1.7.130
Firefox 130.0 on Windows 11 (stable)

**Comment by QNetITQ** [comment]
This bug has already been fixed in v1.7.131.
