### ISSUE TITLE
how to active New Tab Button Like Pinned Tab

### ISSUE THREAD

**Issue by Sarptra** [QNetITQ/WaveFox#21]

**Comment by QNetITQ** [comment]
Open the about:config. Enter the key and click on the add button. The key will appear with the value "true"
![изображение](https://user-images.githubusercontent.com/85301851/151703349-85558d36-f096-4bfa-bd94-84d9a6635011.png)
![изображение](https://user-images.githubusercontent.com/85301851/151703362-48657f63-598e-41ef-b324-2bad44bf29e6.png)

**Comment by Sarptra** [comment]
thanks
