### ISSUE TITLE
"userChrome.WebPage.Rounding.Enabled" flag doesn't work

### ISSUE THREAD

**Issue by dreamsynth** [QNetITQ/WaveFox#212]
After creating and enabling this flag nothing happens.

Firefox Dev 131.0b9
`userChrome.Tabs.Option2.Enabled`
`userChrome.DarkTheme.Tabs.Borders.Enabled`
`userChrome.DarkTheme.Tabs.Shadows.Saturation.High.Enabled`
`userChrome.LightTheme.Tabs.Borders.Enabled`
`userChrome.LightTheme.Tabs.Shadows.Saturation.High.Enabled`
`userChrome.DragSpace.Left.Disabled`
`userChrome.DragSpace.Top.Windowed.Enabled`
`userChrome.Menu.Size.Normal.Enabled`

**Comment by dreamsynth** [comment]
![изображение](https://github.com/user-attachments/assets/19c26337-9b89-460d-9aa7-45b73d6dd40f)
I noticed that the file that is probably responsible for enabling this option does not have an extension.

**Comment by QNetITQ** [comment]
Yes, I forgot to specify the file extension. Although it is not so important in the current release, since the option is not yet finished. If you want to try its final form, download v1.7.132 or transfer the file from there.

**Comment by dreamsynth** [comment]
All right, thanks for the reply!
