### ISSUE TITLE
lepton icons not working

### ISSUE THREAD

**Issue by davidbepo** [QNetITQ/WaveFox#215]
after i updated to firefox 132 i had to update wavefox due to tab size, this version has removed the menu icons option but has a lepton icons option that should so the same, however i see no effect after setting it
![Captura de pantalla de 2024-10-31 19-03-49](https://github.com/user-attachments/assets/1bc45bf0-a967-4f21-b79a-1734dddd85e5)
(menu is dim because screenshot auto closes it but no icons can be seen)

**Comment by QNetITQ** [comment]
This key only allows the use of icons, but does not turn them on. This is, so to speak, a safety key, since the code is third-party. Activate the keys from the list below, depending on their name and what you need.

**Comment by davidbepo** [comment]
![Captura de pantalla de 2024-10-31 19-34-56](https://github.com/user-attachments/assets/14998dbc-cd99-4045-a952-6bb00099245e)
not working either

**Comment by QNetITQ** [comment]
It works, just the key names are a bit confusing.

![изображение](https://github.com/user-attachments/assets/c76bd5f6-5c60-4a60-b060-55cfebd5ecbd)

**Comment by davidbepo** [comment]
i tried copying your config (which differs from readme), nothing
![Captura de pantalla de 2024-10-31 19-53-49](https://github.com/user-attachments/assets/12d1676d-de67-43ac-bb56-505bd7510b16)

**Comment by davidbepo** [comment]
![Captura de pantalla de 2024-10-31 19-55-48](https://github.com/user-attachments/assets/2d8b21a7-d07c-4a86-8946-0304119f4faa)
ok, managed to get it working, the key is
userChrome.icon.panel

**Comment by davidbepo** [comment]
so readme is wrong, this part would need to be changed
![Captura de pantalla de 2024-10-31 19-57-06](https://github.com/user-attachments/assets/bc56bdc9-5bc8-42a4-8499-0f92736822a9)

**Comment by QNetITQ** [comment]
Corrected the description. Now it should be clearer how to enable these keys.
