### ISSUE TITLE
New tab button like pinned tab option leads to new tab button overextending its hitbox

### ISSUE THREAD

**Issue by vavsvirtual** [QNetITQ/WaveFox#22]
When pinned new tab option is enabled the hitbox overextends to the right allowing you to click the button without actually interacting with it, could be because the normal new tab button occupied that space originally. (see below where i've lined them up roughly). Intuitively I would expect this space to be for dragging only.
![image](https://user-images.githubusercontent.com/65417149/151719823-6ba5022d-9dde-4d41-8e19-3412ebcdff81.png)
If it helps the options I've enabled/changed are:
- Wavefox
- Pinned new tab button
- Left drag space set to 0px

And I'm on firefox 96.0.3, feel free to close this issue if this is behaviour that can't change/point me in the right direction if I've missed something that fixes this already listed/reach out for other clarifications.

**Comment by QNetITQ** [comment]
Hi. It can be done. The question is how. I have some ideas, but they need to be tested. When I'm done transferring the settings to the about:config, I'll take care of the new tab button. One way or another, the optimal solution will be found.

**Comment by QNetITQ** [comment]
Transfer settings completed. Now I'll try to remake the new tab button, but it will take some time

**Comment by QNetITQ** [comment]
Done
