### ISSUE TITLE
Padding is broken again on 133

### ISSUE THREAD

**Issue by lastwespoke** [QNetITQ/WaveFox#221]
<img width="323" alt="Untitled" src="https://github.com/user-attachments/assets/e0944159-3cdf-4e03-9707-a81a3edee39c">

**Comment by QNetITQ** [comment]
I can't reproduce this. Are you using the latest release version of the style?

**Comment by lastwespoke** [comment]
Was sure i am, but reinstall fixed the issue. My apologize for inconvenience.
