### ISSUE TITLE
Strange behaviour when tabs exceed the window width

### ISSUE THREAD

**Issue by soustruh** [QNetITQ/WaveFox#23]
Hi,
I have a lot (like 594) tabs in one window and the restyled tabs look strange, check the screenshot please. The tab on the very left is active, the rightmost one is hovered.

![obrazek](https://user-images.githubusercontent.com/3732416/151942842-dc52d171-7d79-43bc-b974-656ad4192ae3.png)

When I open a new window with only a couple of tabs, everything seems OK. Could you please check, if you can reproduce this issue?

Thanks for your great effort anyway! 😊

**Comment by QNetITQ** [comment]
Hi. This behavior is by design. If I leave the active tab the same as the rest, it won't fit into the animation. I can make this behavior optional, but I can't fix the animation bug since I don't have access to the browser's javascript.

**Comment by soustruh** [comment]
Mhm, I am sorry, I probably didn't attach a proper screenshot. My point is: why are the active and the hovered tab so narrow, while all other tabs look normal? I don't know what animations are you talking about, maybe I disabled something before in my about:config? The screenshot above however shows a persistent state, not a point in time during any animations… Check this one please:

![obrazek](https://user-images.githubusercontent.com/3732416/151984614-e193f480-c9ef-4d0c-a2bc-221617688b20.png)

**Comment by QNetITQ** [comment]
Normally tabs should look like this
![изображение](https://user-images.githubusercontent.com/85301851/151992740-1f37874d-2caf-4e55-bc03-ba23a5cf1aed.png)
But there is a problem with animation here. If you click on the new tab button, the new tab will be cut off on the right side
![изображение](https://user-images.githubusercontent.com/85301851/151993130-df284fc9-fcb9-4d82-bea8-a40885c43721.png)
This applies to other animations as well
![изображение](https://user-images.githubusercontent.com/85301851/151993294-e91f2df2-9f02-44a8-af29-9ace17fca3b3.png)
I made the tabs in such a way that they fit into the length that is allocated by the browser

**Comment by soustruh** [comment]
OK, I get your point. I'd just much rather look at the rightmost tabs a bit cut off, than look at all tabs shrinked to the size of pinned when they are active or hovered. 🙁 

![obrazek](https://user-images.githubusercontent.com/3732416/152008169-7ac454f9-4e46-4edb-a74c-b80fc7df11ae.png)

**Comment by QNetITQ** [comment]
I will make this behavior optional.

**Comment by soustruh** [comment]
Thanks a lot! 😍

**Comment by QNetITQ** [comment]
Everything is ready

**Comment by soustruh** [comment]
Oh, I just tested it, it looks great, thank you! 🌈 🦄
