### ISSUE TITLE
Request: Firefox containers tabs background color

### ISSUE THREAD

**Issue by apjyotirmay** [QNetITQ/WaveFox#29]
Hi,

I've always wished for container tabs to be more friendly when it comes to figuring out. Right now, there only goes a subtle highlight behind the tabs. I'm wondering if it's possible for you to color the tab with containers' color.

**Comment by QNetITQ** [comment]
Hello. If you mean something like this, then yes. True, then the fonts can be difficult to distinguish in some situations.
![изображение](https://user-images.githubusercontent.com/85301851/161255695-dd1a0f1a-1d40-4409-8f5b-af605203edec.png)

**Comment by QNetITQ** [comment]
There are several solutions here. You can color the fonts white and add a shadow, but that won't look very minimalistic. You can make the tab color translucent. Then the fonts will always be visible.

**Comment by apjyotirmay** [comment]
Wow! The mock-ups actually look really good!

**Comment by QNetITQ** [comment]
Everything is ready. Minimum browser version 99+
