### ISSUE TITLE
Suggestion: make container colors opaque to avoid overflows

### ISSUE THREAD

**Issue by Loskir** [QNetITQ/WaveFox#31]
<img width="312" alt="изображение" src="https://user-images.githubusercontent.com/21295738/161965723-d3cab73f-7f29-4422-97df-3148800c0060.png">

Maybe mix them with the background color instead of transparent. Should give the same result in theory. Couldn't figure out how to do it myself.

**Comment by QNetITQ** [comment]
I can't make the color of the tabs opaque as the fonts can be hard to see. I wrote about this in #29

**Comment by Loskir** [comment]
If we mix accent color with tabbar color instead of transparent, we get identical results, but the color is opaque

<img width="326" alt="изображение" src="https://user-images.githubusercontent.com/21295738/161993767-4d5e3b6a-e4b1-4b94-b3d0-6297813de871.png">



I've also changed SVGs for inactive container tabs so its corners don't overlap. I like it a lot
<img width="325" alt="изображение" src="https://user-images.githubusercontent.com/21295738/161995641-aa3cdd13-fe9b-4e8d-b39d-a3a4d54ac9c5.png">

Here's my changes: https://github.com/QNetITQ/WaveFox/compare/main...Loskir:main

**Comment by QNetITQ** [comment]
I'll leave it as is. This preserves compatibility with operating systems that support transparency of window frames and code much less. Your version looks interesting, but requires too many changes, in particular, redrawing the SVG.

**Comment by Loskir** [comment]
Fair point
