### ISSUE TITLE
Support dark inactive titlebar color

### ISSUE THREAD

**Issue by kocane** [QNetITQ/WaveFox#32]
I am using the following code to change the color of titlebar when the window in inactive:
```
:root[tabsintitlebar]:is(:not(:-moz-lwtheme), [lwt-default-theme-in-dark-mode]):is(:-moz-window-inactive) .titlebar-color
{
    background-color: #404040 !important;
    color: -moz-accent-color-foreground;
}
```

In the old version (not exactly sure how older than current, but from before all tweaks were moved to about:config), it looked like this without me needing to change much else (Firefox 98):
![image](https://user-images.githubusercontent.com/7694813/162544164-a4f6103d-c645-4066-8aac-2262bbb5b5ae.png)

In the current version and on Firefox 99 it looks like this:
![image](https://user-images.githubusercontent.com/7694813/162544026-365a1da3-94f0-453c-b782-bffe944e90f4.png)

Any idea how I can make it like it was before, with the latest version?

**Comment by QNetITQ** [comment]
Hi. Same code, but color: white;

**Comment by kocane** [comment]
@QNetITQ Right on. This one was perhaps a bit off-topic, but you helped anyway. Thanks!

**Comment by kocane** [comment]
@QNetITQ  little titlebar related question: in older versions it was easily possible to adjust the space above tabs in non-maximized mode. Could this be brought back somehow, thru about:config or something?

**Comment by QNetITQ** [comment]
I didn't think anyone would need it. A little later I will add the ability to control the size of the space for dragging. Only it will apply to all modes, most likely.

**Comment by kocane** [comment]
> I didn't think anyone would need it. A little later I will add the ability to control the size of the space for dragging. Only it will apply to all modes, most likely.

Hmm, I liked it but it's not THAT important. It might be a problem if there's more space in maximised mode as quickly clicking tabs gets harder.

**Comment by QNetITQ** [comment]
Done

**Comment by kocane** [comment]
> Done

Absolutely awesome. Thanks!

**Comment by kocane** [comment]
@QNetITQ Hope it's ok I bring this up again in this albeit random issue, but has the increased drag space functionality, in non-maximized mode, been deprecated :(?

**Comment by kocane** [comment]
@QNetITQ Could you help me getting this to work again with the latest version? I've used this for years but it stopped working now.

```
  :root[tabsintitlebar]:is(:-moz-window-inactive) .titlebar-color
  {
      background-color: #404040 !important;
      color: white !important;
  }
```

**Comment by QNetITQ** [comment]
```
:root[tabsintitlebar]:-moz-window-inactive .browser-titlebar
{
    background-color: #404040 !important;
    color: white !important;
}
```

**Comment by kocane** [comment]
@QNetITQ Hi mate. Do you know if this has changed, yet again, in 135?

**Comment by QNetITQ** [comment]
```
:root[customtitlebar]:-moz-window-inactive .browser-titlebar
{
    background-color: #404040 !important;
    color: white !important;
}
```

**Comment by kocane** [comment]
Thanks again for your work and help.

**Comment by kocane** [comment]
@QNetITQ Sorry for bringing this up time and time again, but do you know if this has changed again?

**Comment by QNetITQ** [comment]
The latest code works for me.

**Comment by kocane** [comment]
@QNetITQ Weird. Looks like it's sorta halfway affected by the color I've set.

![Image](https://github.com/user-attachments/assets/433fe6b4-eb54-4b4a-8618-8da513121951)

**Comment by kocane** [comment]
Alright, I should've tested it directly in the userChrome.css. It's because I use my own .css with toggable tweaks and apparently I had to change `@media (-moz-bool-pref: "userChrome.DarkTitleBar") `to `@media -moz-pref("userChrome.DarkTitleBar")`

Thanks
