### ISSUE TITLE
Unable to setup CSS in Firefox.

### ISSUE THREAD

**Issue by dongltron** [QNetITQ/WaveFox#35]
I always used to be able to and now it simply does not work. Is there something else that could be interfering? I have followed all instructions correctly and all files are in the correct locations. What's going on?

**Comment by QNetITQ** [comment]
Hello. Everything works if done strictly according to the instructions. Can you describe the sequence of your actions, especially at the first step of the installation?

**Comment by dongltron** [comment]
I am running Windows 11, Version 22H2 and Firefox Beta 100, Version 100.0b7. I put the chrome folder in the root directory of the correct profile (C:\Users\ryanl\AppData\Roaming\Mozilla\Firefox\Profiles\gwtkzrbz.Ryan-1587639458823\chrome), and have keys toolkit.legacyUserProfileCustomizations.stylesheets, svg.context-properties.content.enabled, and layout.css.color-mix.enabled all set to true.

To my understanding, this is all that's required to get it working. Is this all correct?

**Comment by QNetITQ** [comment]
Only step 4 is optional. All others are required. Otherwise, it won't work.

**Comment by QNetITQ** [comment]
If your issue is resolved, I close the report.
