### ISSUE TITLE
Linux transparency

### ISSUE THREAD

**Issue by PoSayDone** [QNetITQ/WaveFox#37]
Is transparency going to work on linux, or I'am doing something wrong?

**Comment by QNetITQ** [comment]
I support transparency on Mac and Windows. For Linux, I did not add transparency.

**Comment by QNetITQ** [comment]
I'm closing the report if you have no more questions.

**Comment by SkyyySi** [comment]
Would you accept a PR if someone else were to add Linux transparency?

**Comment by QNetITQ** [comment]
I can't promise. You can send the code. I'll check it out and if everything is ok, I'll add it.
