### ISSUE TITLE
Shadow is cutoff on macOS

### ISSUE THREAD

**Issue by a3r0net** [QNetITQ/WaveFox#4]
![](https://raw.githubusercontent.com/a3r0net/files/dl/misc/waveCssBug-opti.jpg)

Also, not sure where else to tell you this, but this theme is by far my favorite! I sincerely hope you continue perfecting it.

**Comment by QNetITQ** [comment]
Fixed. Please check

**Comment by a3r0net** [comment]
That fixed it.

![](https://raw.githubusercontent.com/a3r0net/files/dl/misc/fixedwavecss-opti.jpg)
