### ISSUE TITLE
Doesen't work

### ISSUE THREAD

**Issue by Fefedu973** [QNetITQ/WaveFox#40]
I followed all the steps but nothing appears

**Comment by QNetITQ** [comment]
You may have selected the wrong profile folder.
![изображение](https://user-images.githubusercontent.com/85301851/167457615-84d29b56-03c8-421e-9ec2-8bbd62c6257a.png)

**Comment by Fefedu973** [comment]
> You may have selected the wrong profile folder.
> ![изображение](https://user-images.githubusercontent.com/85301851/167457615-84d29b56-03c8-421e-9ec2-8bbd62c6257a.png)
> 

no, I chose this one well, that's why I'm confused

**Comment by Fefedu973** [comment]
> You may have selected the wrong profile folder.
> ![изображение](https://user-images.githubusercontent.com/85301851/167457615-84d29b56-03c8-421e-9ec2-8bbd62c6257a.png)
> 

no, I chose this one well, that's why I'm confused

**Comment by QNetITQ** [comment]
The choice of the shape of the tabs is also required.

**Comment by Fefedu973** [comment]
> The choice of the shape of the tabs is also required.

Yes done to but doesn't work

**Comment by QNetITQ** [comment]
Browser and operating system version?

**Comment by Fefedu973** [comment]
> Browser and operating system version?

Firefox 100 and windows 11

**Comment by Fefedu973** [comment]
![image](https://user-images.githubusercontent.com/80718477/167472282-776d390e-9811-4b48-a7ae-1ece67419a26.png)
![image](https://user-images.githubusercontent.com/80718477/167472329-925c6434-3239-4fa1-a990-6de5f6e14375.png)
![image](https://user-images.githubusercontent.com/80718477/167472607-30fcd14c-0425-412f-ad03-eb82e9c375b2.png)
![image](https://user-images.githubusercontent.com/80718477/167472673-5f93a9c7-072c-418c-8d72-4246cf2fcd93.png)
![image](https://user-images.githubusercontent.com/80718477/167472706-5d4b0d06-09f9-4614-99fc-81facc8f9280.png)
![image](https://user-images.githubusercontent.com/80718477/167472756-7482a14f-2a62-40b4-8c7f-362c97ed5f01.png)
![image](https://user-images.githubusercontent.com/80718477/167472798-a2acbf6f-9f3b-49d7-a8be-8353ad09a6b3.png)

**Comment by Fefedu973** [comment]
@QNetITQ

**Comment by QNetITQ** [comment]
That's right. Browser, I hope you restarted after activating the keys? It won't work without a restart.

**Comment by Fefedu973** [comment]
> 

I completely rebooted. even my pc

**Comment by Fefedu973** [comment]
> That's right. Browser, I hope you restarted after activating the keys? It won't work without a restart.

I completely rebooted. even my pc

**Comment by QNetITQ** [comment]
This is strange. Everything seems to be correct. A little later, I will describe in detail all the steps regarding the installation.

**Comment by Fefedu973** [comment]
> This is strange. Everything seems to be correct. A little later, I will describe in detail all the steps regarding the installation.

so do you have an idea of ​​the problem or is it on my side and here it is?

**Comment by QNetITQ** [comment]
There are several ideas. Download Firefox Nightly and try on it. This will eliminate the influence of extensions and profile settings.

**Comment by QNetITQ** [comment]
Take a screenshot of the contents in the chrome folder. Maybe that's the thing.

**Comment by Fefedu973** [comment]
> Make a screenshot of the contents in the chrome folder. Maybe that's the thing.
problem fixed ! in fact I had downloaded wavefox here: https://github.com/QNetITQ/WaveFox/releases/tag/v1.204. when you just had to download wavefox directly by cloning it and downloading it in zip

**Comment by Fefedu973** [comment]
> Make a screenshot of the contents in the chrome folder. Maybe that's the thing.

problem fixed ! in fact I had downloaded wavefox here: https://github.com/QNetITQ/WaveFox/releases/tag/v1.204. when you just had to download wavefox directly by cloning it and downloading it in zip

**Comment by QNetITQ** [comment]
Well, yes. 1.204 should no longer work on version 100. Then I close the report.
