### ISSUE TITLE
Thin Line between Tab and Toolbar

### ISSUE THREAD

**Issue by HuM4NoiD** [QNetITQ/WaveFox#42]
There is a thin line between the selected tab and toolbar.
Tested on Firefox v100.0 with `Style.Chrome`
![image](https://user-images.githubusercontent.com/41481260/168093756-0e2566ba-cb52-4c4c-be1e-2673265677f0.png)

**Comment by HuM4NoiD** [comment]
OS: Windows 11 v10.0.22000 Build 22000
Firefox: v100.0

The thin line is visible at 175% (1.75x) scaling, at integer scaling the line is not visible.

**Comment by QNetITQ** [comment]
I found a few more bugs besides yours. All of them are present at scaling over 100%. It will take some time to fix.

**Comment by QNetITQ** [comment]
Your problem has been fixed. Check

**Comment by HuM4NoiD** [comment]
Yes the problem is fixed now.
Thank you for the speedy and accurate Fix!
