### ISSUE TITLE
Suggestion: Remove blue glow around search/address bar when active

### ISSUE THREAD

**Issue by systwi-again** [QNetITQ/WaveFox#45]
Before/current:

![current](https://user-images.githubusercontent.com/83625333/168959789-475d9db7-d3e2-4c22-81c5-3639c8354d6e.png)

After/potential fix:

![fixed](https://user-images.githubusercontent.com/83625333/168959845-98471bce-b0ee-496a-8e24-c4041b0f7f25.png)

In older versions of Firefox (not sure when the transition period was), the search and address bars _wouldn't_ produce a blue glow when activated. I've always preferred the older design, the blue glow never looked that great in my opinion. Is it possible to add (well, technically remove) this feature to WaveFox? Other than that, WaveFox works really well for me, and I love its customizable group of settings!

**Comment by QNetITQ** [comment]
Highlighting the search bar helps the user interact with the interface. So I'll leave it as is, but you can make changes yourself.

**Comment by systwi-again** [comment]
I understand, you bring up a good point. I'll poke around in the CSS and see what I come up with.

I'll also close this as it seems it won't be added to WaveFox, which is okay.
