### ISSUE TITLE
Firefox 29-40 Style Tabs

### ISSUE THREAD

**Issue by LinkSec64** [QNetITQ/WaveFox#47]
Hey there, I'm using the Chrome-Legacy theme, which is amazing btw, but looks a bit too modern for someone like me. Could we get more solid, FF 29-style tabs? this is what i'm talking about:

![image](https://user-images.githubusercontent.com/104990140/169298657-0251dfe8-3281-4358-a2b8-0bd57e18d65f.png)

**Comment by QNetITQ** [comment]
Hello. Australis tabs are supported. True, without gradients and the height is not 30 pixels, but 32px for technical reasons. The compact interface will bring you as close as possible to this look.

**Comment by QNetITQ** [comment]
If there are no more questions, I will close the report.

**Comment by kocane** [comment]
@QNetITQ maybe the more visible border that goes along the top of the toolbar across the top of the tab, could be replicated in wavefox?

**Comment by QNetITQ** [comment]
The shadow is needed to separate the tab bar from the background. In the screenshots above, everything is clearly visible. On modern themes (White on White / Black on Black), a soft shadow is enough.

**Comment by kocane** [comment]
@QNetITQ Speaking of old Firefox versions; shouldn't the next challenge be to bring back the tabs from Firefox 4 and/or 3? 😄
