### ISSUE TITLE
Shadows for tabs and the navigation bar are only visible on the default theme

### ISSUE THREAD

**Issue by nikzay-git** [QNetITQ/WaveFox#48]
If you apply a custom theme, the shadows around the tabs and the navigation bar disappear

##### Default theme
![Default theme](https://i.imgur.com/vYaeEcJ.png)

##### Custom theme
![Custom theme](https://i.imgur.com/JNlILmv.png)

**Comment by QNetITQ** [comment]
It is not possible to use shadows on AMO themes for technical reasons.

**Comment by nikzay-git** [comment]
Okay, I got it! Thanks for the answer!
