### ISSUE TITLE
Tab Indicator visibility.

### ISSUE THREAD

**Issue by VitalSkib** [QNetITQ/WaveFox#49]
Hi..
I can’t make the Tab Indicator visible.. 
The description says: 
> _Use the option to offset the width of pinned tabs._ 
> _A very high offset is recommended._

What _**option**_ do you mean? 
Any help?
Thanks in advance.

**Comment by QNetITQ** [comment]
Hello. Is there no indicator at all, or is it only missing on pinned tabs? This is the option above.
![изображение](https://user-images.githubusercontent.com/85301851/171485151-07805e29-bd19-420b-aad7-be35ec68e8fe.png)

**Comment by VitalSkib** [comment]
It is invisible at all, not only on the pined tabs, but on all..

**Comment by QNetITQ** [comment]
Now I'll check all the settings. This will take 15 minutes or so.

**Comment by QNetITQ** [comment]
Checked. Everything is working.

**Comment by VitalSkib** [comment]
Hi. Sorry for the delayed answer.. 
Yes, it apparently works, just checked it on a freshly installed Dev Firefox. 
Perhaps something else prevented this from appearing. 
BTW Can you tell me where I can change the height of this indicator from 2 to 3 pixels?
Thanks for your help.. 

PS God, this purple hue everywhere in the program is so annoying and infuriates me. 
This is perhaps the only reason why I look towards Chrome and even Edge sometimes.. ))

![2022_06_04_Tab_Indicator](https://user-images.githubusercontent.com/43848892/171930114-746cc2a0-673a-4fc8-966b-b98e96bff870.png)

**Comment by VitalSkib** [comment]
`BTW Can you tell me where I can change the height of this indicator from 2 to 3 pixels?`
Found it, never mind.. ;)

![chrome_browser_content](https://user-images.githubusercontent.com/43848892/171933682-0888902c-d32d-4740-ad33-45e1d15745b9.png)
