### ISSUE TITLE
Transparency on Linux (KDE + ForceBlur)

### ISSUE THREAD

**Issue by QNetITQ** [QNetITQ/WaveFox#50]
Trying to add transparency to Linux.

**Comment by polucifier** [comment]
Hello, I am from reddit.
I have force blur configured, but as far as I know force blur doesn't apply transparency by itself, it only blurs already transparent elements. Compare (the first is force blur off, the second on):
![Screenshot_20220602_100223](https://user-images.githubusercontent.com/91974475/171572448-b9bb184d-b876-4f85-ad66-53c05a5163fe.png)
![withblur](https://user-images.githubusercontent.com/91974475/171572517-abe78ab4-0132-4ec9-8889-a35342dc971a.png)
I am applying transparency using kwin's window opacity property.
In case you need to know how:
1. Open the window you want to make transparent
2. Right click on titlebar or press Alt+F3
3. More Actions -> Configure Special Window Settings
4. Add Property -> Active Opacity

The disadvantage is that this method applies transparency to the whole window. If you want me to use a different way please tell me.

**Comment by QNetITQ** [comment]
If transparency is implemented like this, then I don’t need to do anything at all. Everything works, but I would not use such transparency. The title bar is one thing, but the content...
![изображение](https://user-images.githubusercontent.com/85301851/171618302-c8e6cf86-4dc9-41b5-8d1c-f3ded6a4472f.png)

**Comment by QNetITQ** [comment]
In general, it worked out. But in a very crude way. I'll post a test style here a little later.
![изображение](https://user-images.githubusercontent.com/85301851/171637187-da470ec8-a873-4d5c-8672-a91996b05bd1.png)

**Comment by polucifier** [comment]
> In general, it worked out. But in a very crude way. I'll post a test style here a little later. ![изображение](https://user-images.githubusercontent.com/85301851/171637187-da470ec8-a873-4d5c-8672-a91996b05bd1.png)

Awesome :+1:

**Comment by polucifier** [comment]
The bar is only transparent when scaling the window down, otherwise it's black. I can record you a video a little later.

**Comment by QNetITQ** [comment]
I have the same. Try to activate the keys below, it may help.
layers.acceleration.force-enabled
gfx.webrender.all
gfx.webrender.enabled

**Comment by QNetITQ** [comment]
I have such a suspicion that in the full screen transparency is not provided by the system itself. The taskbar loses transparency when the window is full screen. Apparently Force Blur behaves in a similar way. There is nothing to worry about, since the window can simply be stretched. It will be like a full screen, but with transparency.

**Comment by polucifier** [comment]
I usually don't use window titlebars, and I haven't encountered any problems with that until now. This is what I get when they are disabled (before & after activating the keys you provided):

https://user-images.githubusercontent.com/91974475/171698366-468dc140-c2e4-4eff-9f5c-f58a9aad53b6.mov

I guess this is not the problem of firefox? Probably I have to find some other ways to remove them or accept them eventually.

But if I enable the titlebars back, everything is perfect, except for the fullscreen (the one that appears after pressing F11):

https://user-images.githubusercontent.com/91974475/171698392-a269a17e-9dce-4e4c-8b25-adbaed72d431.mov

**Comment by polucifier** [comment]
I want to clarify things a little more.

> The bar is only transparent when scaling the window down, otherwise it's black. I can record you a video a little later.

This doesn't make sense anymore as my window titlebars (those where minimize, maximize and close buttons are) were disabled in system settings and for some reason this was breaking the transparency and the tabbar was flickering when resizing the window. Sorry for this.

However, when titlebars are back, transparency works both on minimized and maximized (fullscreen) windows, it only doesn't in F11-mode. Hope this helps :)

**Comment by QNetITQ** [comment]
Turned on transparency everywhere where there is no black background. Maybe in the future it will be possible to bypass it.
