### ISSUE TITLE
Transparency on MacOS

### ISSUE THREAD

**Issue by QNetITQ** [QNetITQ/WaveFox#51]
Transparency does not work on MacOS since Firefox 103(102?)+

**Comment by QNetITQ** [comment]
MacOS transparency testing. Doesn't work on Firefox ESR.

**Comment by adhdvator** [comment]
This theme worked for me. Hope it's helpful.

https://github.com/Tnings/MacosVibrant

**Comment by QNetITQ** [comment]
Firefox Beta v102b6 works for now, but this may change from 102b7+

**Comment by QNetITQ** [comment]
MacOS transparency added for Firefox 102+

**Comment by FormalSnake** [comment]
> MacOS transparency added for Firefox 102+

How do i enable it?

**Comment by QNetITQ** [comment]
It is active by default on the browser's system theme.

**Comment by FormalSnake** [comment]
> It is active by default on the browser's system theme.

I see it now, it would be handy if it worked with themes like tokyonigh tho

**Comment by QNetITQ** [comment]
AMO themes are not compatible with system effects, for many reasons.
