### ISSUE TITLE
Fallback for Firefox CSS if Windows uses custom theme

### ISSUE THREAD

**Issue by kujou-kju** [QNetITQ/WaveFox#52]
I recently found out about WaveFox and MicaForEveryone and I loved it. Later I found the MSSTYLE File of the Windows 11 Dark Mode Theme created and used for the Rectify11 Project/Mod. Now my Windows has full Dark Mode but Firefox started looking kinda weird. The enabled Mica transparency has gone and my Window Control Buttons now look hella weird. For the Button issue I found some fallback css some time ago which revert the default ones but there's still the transparency issue. Is there any way someone could implement or create a theme fallback build in into WaveFox for the Windows CSS that prevent Firefox from changing some elements breaking the theme?

The Window Controll Fallback CSS I found: https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_fallback_for_custom_windows_theme.css

## Specs
OS: Win 11 Pro
Firefox v101.0
Windows Theme: Rectify11 dark mode
MicaForEveryone v1.0.6.2
<details>
  <summary>Desktop Screenshot</summary>

![grafik](https://user-images.githubusercontent.com/23724383/171728558-b4bfa7ea-2c79-4881-856d-c86457678c01.png)
</details>

**Comment by QNetITQ** [comment]
Somehow later I can try to change it, but there are no guarantees that everything will work as with native themes.

**Comment by QNetITQ** [comment]
Everything should be fine now, but the accent color is only available on native themes.

**Comment by QNetITQ** [comment]
I will close the issue. Write if something is wrong.
