### ISSUE TITLE
Wierd Issue

### ISSUE THREAD

**Issue by sumeshir26** [QNetITQ/WaveFox#53]
While hovering over any tab which is not currently active, this happens:
![Uploading image.png…]()

**Comment by sumeshir26** [comment]
![Uploading image.png…]()

**Comment by sumeshir26** [comment]
![image](https://user-images.githubusercontent.com/68823982/171976643-ef2a02ef-6751-4a0a-9605-5d98b18af343.png)

**Comment by QNetITQ** [comment]
You have not activated the key "layout.css.color-mix.enabled"

**Comment by sumeshir26** [comment]
Ok thabks
