### ISSUE TITLE
Toolbar (Full Transparency)

### ISSUE THREAD

**Issue by QNetITQ** [QNetITQ/WaveFox#56]
Approximate goal
![Снимок](https://user-images.githubusercontent.com/85301851/174320267-5264f96e-7436-44fc-97f3-eba706cd4051.PNG)

**Comment by pratyakshm** [comment]
Looks good so far. Have you tried demoting other tabs by reducing their font weight? As an additional but strongly recommended step, you could also introduce drop shadow below the active tab. This is how it looks in Edge:
![image](https://user-images.githubusercontent.com/54220235/174424330-eb0af9ed-a0ab-4f96-8370-4b57fb7f9195.png)

 I have observed that the active tab shadow helps easily distinguish between other tabs.

I do not know if this is possible, but I would love it if it were. I think others will like it too.

What are your thoughts on this?

**Comment by QNetITQ** [comment]
Hello. I can’t just take and change something, as I depend on compatibility issues with different operating systems, browser themes, and even my own options. The font size depends on the OS. They can be changed, but again there are compatibility problems. My shadows are already implemented and made as they are. You can use my style as a base and make your own changes. You don't have to consider compatibility.

**Comment by QNetITQ** [comment]
Done
