### ISSUE TITLE
WaveFox v1.2.103 Beta

### ISSUE THREAD

**Issue by QNetITQ** [QNetITQ/WaveFox#59]
Refactoring. Removing options that are insignificant for the user.

**Comment by nikzay-git** [comment]
Adjusting the saturation of separators and disabling the first separator were significant options :(

**Comment by QNetITQ** [comment]
As for the first separator, maybe I'll hide it by default without any options. Not decided yet. The separators will have 50% of the text color. Less will be hard to see, more is too bold.

**Comment by pipashu** [comment]
On macOS, Firefox b103, PhotonTabs, the first tab and the green fullscreen key gap are too tight.

**Comment by QNetITQ** [comment]
You're right. I'll fix this soon.

**Comment by QNetITQ** [comment]
v1.2.103 is now in pre-release status

**Comment by kocane** [comment]
If the first seperator is disabled by default it's ok with me. In my opinion it looks oddly placed anyway.

Did the option to change the new tab button also get removed?

**Comment by QNetITQ** [comment]
There were too many problems with this button. It deformed when scaling. It is possible to fix, but then the hitbox becomes too large. And when I moved the tab separators down a level for compatibility with pinned tabs, it became impossible to create the same for the new tab button. Then I decided to remove it and leave the usual, but slightly modified.

**Comment by kocane** [comment]
> There were too many problems with this button. It deformed when scaling. It is possible to fix, but then the hitbox becomes too large. And when I moved the tab separators down a level for compatibility with pinned tabs, it became impossible to create the same for the new tab button. Then I decided to remove it and leave the usual, but slightly modified.

Understandable. I guess it's also fair to categorize that particular feature as insignificant.

**Comment by QNetITQ** [comment]
Release version changed to v1.3.102
