### ISSUE TITLE
Macos Vibrancy isn't really showing.

### ISSUE THREAD

**Issue by teeshowtime1** [QNetITQ/WaveFox#60]
<img width="1680" alt="Screen Shot 2022-06-28 at 10 35 10 AM" src="https://user-images.githubusercontent.com/108351147/176206405-9d96d626-8758-489d-bf4c-8f948e00c27a.png">
While there is a certain color change, I don't really see it.
I am using Firefox 102.0

**Comment by QNetITQ** [comment]
Hello. Do you have a system theme selected in your browser?

**Comment by teeshowtime1** [comment]
Yes.

**Comment by FormalSnake** [comment]
What is vibrancy? and how do i enable it?
