### ISSUE TITLE
Bug when fullscreen on macOS

### ISSUE THREAD

**Issue by koihia** [QNetITQ/WaveFox#61]
<img width="1280" alt="Screen Shot 2022-07-02 at 16 48 53" src="https://user-images.githubusercontent.com/30551185/176993859-167393ca-5c93-4928-85f9-0bd308182864.png">

This happens when I try to access the menu bar on macOS when fullscreen.

Firefox 102.0
WaveFox v1.2.102

**Comment by QNetITQ** [comment]
Hello. Try v1.2.103 Beta.

**Comment by koihia** [comment]
Thank you for your quick reply! I downloaded v1.2.103 from the main branch and the bug is still there.

**Comment by QNetITQ** [comment]
This is the default behavior. Browser bar offset is difficult to turn off, for various reasons. I can turn off transparency in full screen and leave it in other modes.

**Comment by QNetITQ** [comment]
Done

**Comment by QNetITQ** [comment]
Found a better solution.
