### ISSUE TITLE
Additional Keys appear to not work

### ISSUE THREAD

**Issue by SnoutBug** [QNetITQ/WaveFox#62]
When adding any of the mentioned additional keys like 
`userChrome.LeftSideDragSpace-Disabled`
nothing appears to happen after restarting. That is the case for any key.

Is there anything else that needs to be activated before that?

Arch Linux, Gnome 42, Firefox 102

**Comment by QNetITQ** [comment]
Hello. If you followed the instructions exactly, then everything should work. I can assume that you are using v1.2.102 with keys from v1.2.103.

**Comment by QNetITQ** [comment]
Too late. I'm almost done with the Beta. In a few days it will be a new release.
