### ISSUE TITLE
Missing loaded animation on tabs

### ISSUE THREAD

**Issue by CDanilo25** [QNetITQ/WaveFox#63]
In the standard Firefox theme, there is a little animation when a tab completes its loading, a circle that grows from behind the favicon.
This effect is currently missing on my setup, maybe I have missed some flag in about config?

Firefox 102.0.1
WaveFox 1.3.102
userChrome.WaveFoxTabs-Enabled
Windows 11

**Comment by QNetITQ** [comment]
Hello. The download completion indicator on tabs is disabled because it is not compatible with the outer rounding of tabs. It is possible to turn it on, but not very easy.

**Comment by CDanilo25** [comment]
Oh, ok! I thought it was some compatibility or setup error on my side.
Thanks for the clarification :)

**Comment by QNetITQ** [comment]
Added indication of the end of loading tabs.
