### ISSUE TITLE
Transparency not working on Windows 11

### ISSUE THREAD

**Issue by jonkke8** [QNetITQ/WaveFox#64]
Firefox Stable version 102.0.1
![image](https://user-images.githubusercontent.com/45978346/180273245-9526a9af-937f-4279-a5b8-c93ff7bef7b0.png)
Also just seems strange looking over all, for example the minimize, maximize and close buttons all are different from the Windows default ones

**Comment by QNetITQ** [comment]
Hello. Such window control buttons can be in the case of using a third-party Windows theme. Not all third-party themes can work with transparency.

**Comment by jonkke8** [comment]
Is there no way to force it to work?

**Comment by QNetITQ** [comment]
You have a choice. Use native Windows themes. Everything works there. Alternatively, contact the developers of your third-party theme and ask them to make the theme compatible with transparency. There is no third.

**Comment by jonkke8** [comment]
Ok thanks :)
