### ISSUE TITLE
userChrome.WindowsSystemEffects-Enabled not working

### ISSUE THREAD

**Issue by tangymc** [QNetITQ/WaveFox#66]
I'm on Windows 11. I added the flag but the transparency effect isn't showing even after restarting.
![image](https://user-images.githubusercontent.com/74885686/181815760-62a46c16-7577-4b47-8cd1-344368fd46eb.png)

**Comment by QNetITQ** [comment]
Windows 11 does not support transparency by default. Download the MicaForEveryone

**Comment by tangymc** [comment]
> Windows 11 does not support transparency by default. Download the MicaForEveryone

I've already installed it and added firefox to the list.
![image](https://user-images.githubusercontent.com/74885686/181819429-ba6296d7-914c-4aa0-b773-8f9ddbef228d.png)

**Comment by QNetITQ** [comment]
Try global rule instead.

**Comment by tangymc** [comment]
> Try global rule instead.

Still not working,
![image](https://user-images.githubusercontent.com/74885686/181819993-2f07d674-e038-4899-8c93-5218a88be93c.png)

**Comment by QNetITQ** [comment]
Everything works. Look for the problem on your side.
![изображение](https://user-images.githubusercontent.com/85301851/181831308-7dcba7e1-1c9b-4f49-82e5-ef38a871d5bf.png)

**Comment by tangymc** [comment]
> 
Seems that Version 1.1.0.0 of MicaForEveryone doesn't have acrylic option. Lemme try installing the version that you have and see if it works.

**Comment by tangymc** [comment]
Nvm. I was able to do it. Thx :)

**Comment by disgracedtrash** [comment]
> Nvm. I was able to do it. Thx :)

I'm having similar issues. Can you explain how you got it working?
