### ISSUE TITLE
Does not work with AeroGlass

### ISSUE THREAD

**Issue by logoffon** [QNetITQ/WaveFox#67]
WaveFox v1.3.103.2, Firefox 102.1.0esr, Windows 10 v1909 (w/ [AeroGlass](http://web.archive.org/web/20220616021440/https://www.glass8.eu/) installed)

![image](https://user-images.githubusercontent.com/7828523/182020014-3cdc3175-ee96-4bbe-b2e1-0d6f3a2bad1e.png)

Even with `userChrome.WindowsSystemEffects-Enabled` set to True, it still uses the default look. There doesn't seem to be any colorization either.
A window of Edge 103 (with ` --disable-windows10-custom-titlebar` flag added) is shown for comparison.

**Comment by QNetITQ** [comment]
Firefox 102 ESR is not supported. The minimum version is Firefox 103. For everything to work, you need to select the system theme in the browser and turn off the accent color.

**Comment by logoffon** [comment]
Thanks, got it working now.
![image](https://user-images.githubusercontent.com/7828523/182027279-7747ce76-5d14-4e4b-9655-3e5ae4403f58.png)
