### ISSUE TITLE
Window buttons when the tabs on bottom

### ISSUE THREAD

**Issue by nikzay-git** [QNetITQ/WaveFox#68]
Is it possible to move window buttons (minimize, maximize and close the window) to the right of the address bar to the very top right of the window when the tabs are at the bottom?

**Comment by QNetITQ** [comment]
This mode is classic. You may need to activate the title bar in the settings.
![изображение](https://user-images.githubusercontent.com/85301851/182900252-61d4f7c5-7d05-4ce4-9921-90541232ec3e.png)
