### ISSUE TITLE
Rectangular style

### ISSUE THREAD

**Issue by ShuiHuo** [QNetITQ/WaveFox#69]
Can you make a `border-radius: 0px` style? I don't like rounded corners, especially right-click menus and two buttons next to each other (like bookmarks). It feels ugly.

**Comment by QNetITQ** [comment]
The style below will suit your requirements better.
https://github.com/leadweedy/Firefox-Proton-Square

**Comment by ShuiHuo** [comment]
That project is not customizable enough and convenient

**Comment by QNetITQ** [comment]
As an option, most likely, I will not add it. You have two options. The first one is rough, but works on the entire toolbar and on all elements. Some of the elements may look strange. Place these lines at the very bottom of the userChrome.css

:root *
{
    border-radius: 0px !important;
}

The second one is official, so to speak, but it may not work for all elements.

:root
{
    --arrowpanel-menuitem-border-radius: 0px !important;
    --toolbarbutton-border-radius: 0px !important;
    --tab-border-radius: 0px !important;
    --arrowpanel-border-radius: 0px !important;
}

To change the content of browser pages, userContent.css is needed, but my style does not provide this file. You can take it from the style I posted above.

**Comment by ShuiHuo** [comment]
Copy some code from Firefox-Proton-Square and paste it into userChrome.css. I've done what I need. Thank you very much for your help.
<details>
  <summary> </summary>
While I'd love for you to add options to this project, it's okay not to.  n(*≧▽≦*)n   ( >﹏<。)～
</details>
