### ISSUE TITLE
Transparent if in window, black if maximized

### ISSUE THREAD

**Issue by CavaleriOmar** [QNetITQ/WaveFox#70]
As per title, I managed to enable transparency (Garuda Linux - arch based - + KDE Plasma 5.25).
I set Proton for appearance, and transparency of the toolbar as well, as visible in the first screenshot, but that transparency breaks when maximizing the window, becoming a black background as seen in the second.

![Screenshot_38](https://user-images.githubusercontent.com/54171779/185736557-420e51e4-6602-402d-8bd5-3dd7babcb209.png)
![Screenshot_39](https://user-images.githubusercontent.com/54171779/185736593-7187e620-8b20-4c24-9ceb-911900b7d12d.png)

**Comment by QNetITQ** [comment]
I can't do anything about it. This is how the browser window rendering engine works on Linux systems. Only Mozilla can fix this. I can advise you to manually stretch the window or use the title bar. With the title bar, transparency works fine in all modes.
