### ISSUE TITLE
duplicate icon buttons

### ISSUE THREAD

**Issue by adzkii-i** [QNetITQ/WaveFox#71]
![sshot-2022-08-22-20-11-41](https://user-images.githubusercontent.com/38789311/186000161-9199a863-3597-424c-9e73-82d05f195c23.png)

not sure why i'm getting duplicate icon button thing, am i missing something?

**Comment by QNetITQ** [comment]
The buttons on the background belong to the operating system and are not clickable under any circumstances. Only Mozilla can fix this.

**Comment by adzkii-i** [comment]
> The buttons on the background belong to the operating system and are not clickable under any circumstances. Only Mozilla can fix this.

It only happens when i switch to Wavefox, but any other chrome.css doesn't happen.

**Comment by QNetITQ** [comment]
I checked everything again. There is no way to hide duplicate buttons. I'll leave it as is.
