### ISSUE TITLE
popup blocker message error.

### ISSUE THREAD

**Issue by Hellements** [QNetITQ/WaveFox#72]
Hello there,
I'm using WaveFox on Firefox 104 x64 with the following commands enabled: 
userChrome.AdditionalContainerIndicator-Enabled
userChrome.CompactContextMenu-Enabled
userChrome.OneLine-Enabled
userChrome.ProtonTabs-Enabled
userChrome.ResponsiveBookmarksBar-Enabled
userChrome.SelectedTabHighlight-Enabled
When I go to a site and click on a link that opens a popup page, a popup blocker message appears on the screen top right, and it causes a layout “bug” on the Firefox top bar.
Sorry, I don't have a screenshot, but I'm sure you can reproduce the error.
Thanks in advance.

**Comment by QNetITQ** [comment]
I am unable to reproduce this behavior. Give me a link that causes this behavior.

**Comment by Hellements** [comment]
Hi,
Unfortunately, I don't remember what site I visited that triggered the pop-up blocker message.
It's not a specific site, but any site that tries to open a pop-up link.
On this site, you can see the message I'm talking about under the “What are pop-ups?” section. It says, “Firefox prevented this site from opening a pop-up window. Options”. https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting
So when that message appears, the layout gets messed up when using the options I described before.
I hope that helps you.
Thanks.

**Comment by QNetITQ** [comment]
Something like this. I will update the style soon.
![изображение](https://user-images.githubusercontent.com/85301851/186462481-cbf1ca92-31e0-4a88-9811-7e2600dd1f14.png)

**Comment by Hellements** [comment]
Yes. That's exactly what I was talking about.
No need to rush to get an update, friend. I don't get that message very often.
Again, thank you.

**Comment by QNetITQ** [comment]
![изображение](https://user-images.githubusercontent.com/85301851/186713138-11b202fb-d7dd-4a9b-94be-537dfed44daf.png)
Now everything should be fine.

**Comment by QNetITQ** [comment]
Fixed some minor bugs. I'm closing the issue report.

**Comment by QNetITQ** [comment]
Testing new implementation

**Comment by QNetITQ** [comment]
Checked. No bugs found.
