### ISSUE TITLE
All white theme?

### ISSUE THREAD

**Issue by 0oWow** [QNetITQ/WaveFox#73]
Hello, I remember a long while back, your theme supported my ability to have a white-on-white color theme.  Basically it was all white.  However, I have since removed the version that allowed me to do that.  Will you please recommend changes to the latest release that I can make to my personal copy so that I can have an all-white theme again?  Thanks in advance!

Edit:  By all-white, I mean keeping the shadows and borders of the tabs, while at the same time all-white.  Currently I can make it all-white, but all borders and shadows go away if I do.

**Comment by QNetITQ** [comment]
If you don't want Firefox to follow the system theme, just choose a light theme in the browser itself. If you want to change the background to pure white, then the recommendations here will depend on the OS you are using.

**Comment by 0oWow** [comment]
I'm using Win 10/11 and KDE Linux, but mainly Windows.  I try other Firefox themes (White 10, for example) but it just makes everything flat and borderless.  The tab bar is just a flat white background with text.  It did not used to do this with some of your earlier releases, however I have deleted your old releases so I can't get it back.

**Comment by QNetITQ** [comment]
#navigator-toolbox
{
    background-color: white !important;
}

**Comment by 0oWow** [comment]
Sadly that is not working for me.  I placed at the top of the userChrome.css file just above #main-window{}.

I'm beginning to wonder if this is a restriction from Mozilla.

**Comment by QNetITQ** [comment]
It must be placed at the very bottom. The last value is always taken.

**Comment by 0oWow** [comment]
Thank you for your assistance!  After checking my home installation, I see that it is all white (Windows 11) versus the Windows 10 at work.  Evidently I have something different and I will work to resolve that.
