### ISSUE TITLE
Border on the left and top sides of the screen during full screen video playback on Firefox

### ISSUE THREAD

**Issue by fieraoh** [QNetITQ/WaveFox#77]
![image](https://user-images.githubusercontent.com/72320316/195159426-d8086ea2-25fa-4de8-b233-cf36b59c39b9.png)

I have verified that the issue is not related to the MicaForEveryone project.

**Comment by fieraoh** [comment]
The issue is not limited to YouTube, using Firefox in full-screen mode yields the same result.

**Comment by QNetITQ** [comment]
I'll see what i can do.

**Comment by QNetITQ** [comment]
This is a browser bug and it only happens under special conditions. I can't do anything here. Read issue #34 if you're interested in the details.
