### ISSUE TITLE
[Request] is it possible to hide "world" favicon that appears before actual page favicon loads? 

### ISSUE THREAD

**Issue by Minibus93** [QNetITQ/WaveFox#78]
Hello, I'll include a brief video that should clarify better

https://user-images.githubusercontent.com/73554423/196661747-4495378b-74e6-4028-bea7-d4256bb00a29.mp4

I find that "world" favicon annoying and would really love to hide it, do you know if it's possible to do so?

Thanks for mainteining WaveFox!

**Comment by QNetITQ** [comment]
I can't reproduce this effect. Try the code below

`
.tab-icon-image:not([src], [crashed], [sharing], [pictureinpicture], [busy])
{
    content: ( your image ) !important;
}
`

**Comment by Minibus93** [comment]
Code didn't work, but it gave me an idea that helped me figuring out what to look for.

Removing lines #586-603 fixed this for me, so thanks for the help!

**Comment by QNetITQ** [comment]
I re-examined this issue. Made a small change. Now the globe icon will not be displayed when opening or closing a tab.

**Comment by Minibus93** [comment]
Thanks for futher looking into this! The attention to details you put into WaveFox is really astonishing!
