### ISSUE TITLE
Question regarding commit 8eeb610

### ISSUE THREAD

**Issue by Charsy89** [QNetITQ/WaveFox#79]
How is the code obselete? I don't see a problem with it...
Australis (and I'd imagine WaveFox) style looked much better with the rounded button, imo.
It's not much of a problem, I can just add the code back into my own userstyle. I just wanted clarification on how it's "obselete".

**Comment by QNetITQ** [comment]
I also like the rounded button, but in Firefox 106+ there are other buttons on the tab bar by default and I would not want to break the symmetry of the elements both in location and in appearance. I'll think of an alternative implementation of the tab bar buttons, but I can't promise anything.

**Comment by Charsy89** [comment]
I see, thanks. Good luck!
And thanks for this project, by the way!
