### ISSUE TITLE
Container colors on tabs

### ISSUE THREAD

**Issue by kocane** [QNetITQ/WaveFox#8]
First off - thanks for this style. It looks awesome, especially in the compact mode. Your work is really appreciated.

I'm a heavy user of containers but it seems like there is no color on the tabs to indicate that they're a container.

Would it be possible to make this?

Also, is it possible to hide this seperator on the first tab but keep them on the following tabs?
![image](https://user-images.githubusercontent.com/7694813/130422130-ec62e988-bf34-4387-9c7a-e338f8705426.png)

**Comment by QNetITQ** [comment]
Hi. As for the separator, the code below should hide it

.tabbrowser-tab[first-visible-unpinned-tab]
{
    background-color: transparent !important;
}

There is an indication of containers, at least in nightly. There seems to be no containers in the release
![изображение](https://user-images.githubusercontent.com/85301851/130427435-10584b89-dd9d-4548-89f4-ad6c01fa6dcb.png)

**Comment by kocane** [comment]
Ah, it was because I still had the "browser.proton.enabled" set to false. Enabling it bought the color back.

And the seperator is hidden with the code you provided.

Thanks again.
