### ISSUE TITLE
Tabbar color in Linux

### ISSUE THREAD

**Issue by kocane** [QNetITQ/WaveFox#81]
I'm trying out KDE Plasma and obviously want to use your style there as well.

I checked that all the requires keys are set, and I've enabled the Australis theme but it looks all bland and solid-color.
![image](https://user-images.githubusercontent.com/7694813/197363013-998eed2a-9a45-4a2e-9f5a-2d834f770a43.png)

The only time I notice anything is when hovering above a tab:
![image](https://user-images.githubusercontent.com/7694813/197363026-8475bfb7-0955-40d3-a290-a9ef9df63cc0.png)

What am I missing?

**Comment by QNetITQ** [comment]
I don't see any issues on my side. Although I checked on Firefox 107 Beta. Firefox 106 update has not come to me yet.
![изображение](https://user-images.githubusercontent.com/85301851/197364698-8ec5f4dd-5eb9-4c37-affe-7e27c1353db1.png)

**Comment by kocane** [comment]
I'll try and see once you get 106 :-)

**Comment by QNetITQ** [comment]
I checked several screenshots with color capture. I don't think this is a bug. It's just that the color of the tab bar is almost the same as the color of the toolbar. Try turning on the shadow or change the theme to something else. If you have KDE 5.25+, then you can activate the accent color as on Win10/11.

**Comment by QNetITQ** [comment]
No interface issues found. (Firefox 106.0.1 + WaveFox v1.5.106.1)
![изображение](https://user-images.githubusercontent.com/85301851/197896787-a8b49b75-05bd-47a8-8529-dfedbc9b5bba.png)
