### ISSUE TITLE
(Windows) minor annoyance: titlebar buttons don't cope with fractional scaling

### ISSUE THREAD

**Issue by V3XATI0N** [QNetITQ/WaveFox#83]
In Windows, the close/maximize/minimize buttons on the titlebar aren't entirely obscured by the widgets provided by this theme when the a fractional scaling factor is used.

**Comment by QNetITQ** [comment]
Mozilla made so. I can only advise you to set the scaling factor recommended by the operating system (100% / 125% / 150%, etc.)

**Comment by V3XATI0N** [comment]
it is set to 175% which is an option as with 100/125/200 etc, i'm not doing anything weird

**Comment by V3XATI0N** [comment]
in pictures:
![snip1](https://user-images.githubusercontent.com/5502824/199564692-0abe3535-40ed-4fc9-a6c5-42bf8dbc30ba.png)
![snip2](https://user-images.githubusercontent.com/5502824/199564691-4f4fc94f-7232-4857-b2c5-6b16875fdc71.png)

**Comment by QNetITQ** [comment]
There is no good solution for these buttons. Mozilla does not suggest using transparency on Windows 10/11 at all. I can't disable browser buttons. System ones are drawn but not clickable. Just ignore this moment. When the developers add support for the system design of Windows 11, these buttons will no longer be a problem.

**Comment by V3XATI0N** [comment]
i see. thanks! again!
