### ISSUE TITLE
Hovering unfocused tab lets its background unchanged and makes its corners black

### ISSUE THREAD

**Issue by victorbnl** [QNetITQ/WaveFox#84]
I am using Firefox 106.0.2 on Linux with a dark theme. I have the latest WaveFox and I am using Chrome tabs style.

When I hover an unfocused tab, the left and right corners become black. The background of the tab remains unchanged.

I have the same issue with Edge tab style, and I guess it would be the same with every style that has corners.

![image](https://user-images.githubusercontent.com/39555268/199717494-0de9fb34-1495-423b-9d1a-8e8d9ef3a93e.png)

**Comment by QNetITQ** [comment]
`layout.css.color-mix.enabled` > true
It's all written in the instructions.

**Comment by victorbnl** [comment]
Right, I was sure I had it enabled. Thanks
