### ISSUE TITLE
Features/Question

### ISSUE THREAD

**Issue by ZachTheDev** [QNetITQ/WaveFox#85]
Love this!
Trying to make firefox look like chrome. The following would make that happen :)

- [ ] An ability to round the 'Omnibox' (search box/URL bar)
- [ ] Change the hamburger menu to three vertically stacked dots
- [ ] Swap the location of the user profile icon with the '>>' icon
- [ ] Align the search tab 'V' icon to the top next to the minimize controls
- [x] Circle around the '+' new tab button
- [ ] Ability to modify active tab color
- [ ] Ability to modify non-active tab color
- [ ] Ability to modify frame color (both when active and not)
- [x] Remove right facing tab separator when the tab is rightmost

Thanks!

**Comment by QNetITQ** [comment]
This project does not aim to replicate the look and feel of Chrome/Edge or any other interface. It is based on Mozilla's Proton UI, but with edits to the most controversial points and the most frequent user requests. I will make some changes from your list, but a little later. If you are interested in Google Chrome replication, take a look at something like [this.](https://github.com/muckSponge/MaterialFox)
