### ISSUE TITLE
Containers not stretching to the full width of the tab 

### ISSUE THREAD

**Issue by Tnings** [QNetITQ/WaveFox#86]
I am not sure if this is intentional or not but having the container indicator being just a dot makes it a little hard to see, is there a way to make it span the full tab?

<img width="446" alt="image" src="https://user-images.githubusercontent.com/55812511/200192339-e2d17475-d067-4ab1-bc42-b60411ccdffb.png">

**Comment by QNetITQ** [comment]
Activate the key "userChrome.AdditionalContainerIndicator-Enabled" or/and you can install v1.5.107. It's pretty much done, just waiting for Firefox 107.0 to be released on the Beta update channel to check the style before the final release.
