### ISSUE TITLE
System effects don't work

### ISSUE THREAD

**Issue by Pico109** [QNetITQ/WaveFox#89]
### System effects like acrylic or mica don't seem to work, titlebar matches accent color instead.
![image](https://user-images.githubusercontent.com/81302994/202244133-cc7a40c9-2247-405f-bcd7-403d3ccb5fa2.png)

**Versions**
- Windows 11 Version 22H2 (OS Build 22621.819)
- Firefox 107.0
- WaveFox v1.5.107 
- Mica For Everyone 1.2.0.0   
<br>

The `chrome` folder is situated in my profile folder.

Mica For Everyone is installed with seemingly correct configurations. I've tried messing with the advanced options and specifying "firefox" as a rule (process).

I've set these keys in to _true_ in `about:config`
-   `toolkit.legacyUserProfileCustomizations.stylesheets`
-   `svg.context-properties.content.enabled`
-   `layout.css.color-mix.enabled`
-  `userChrome.WaveFoxTabs-Enabled`
-  `userChrome.WindowsSystemEffects-Enabled`
-  `userChrome.SemiTransparentToolbar-Enabled`

And i have completely purged Firefox from my system using BCU and reinstalled WaveFox to no avail.

Pics:
![image](https://user-images.githubusercontent.com/81302994/202244906-40dbaf4e-fe06-49dd-aba7-53fb43801512.png)
<img src="https://user-images.githubusercontent.com/81302994/202238605-fa55c907-8b0a-4cd0-816c-3bb5f54e91f9.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/81302994/202235244-ca12785a-1952-477c-97cc-24ea0fb49cff.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/81302994/202236093-0148095c-406f-46df-8fea-27a6fecedd69.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/81302994/202236009-3aa1eac9-0f9f-4e01-ab8c-6beea28c1901.png" width=50% height=50%>

**Comment by QNetITQ** [comment]
The accent color must be disabled in the system.

**Comment by Pico109** [comment]
Welp that fixed it.

**Comment by Pico109** [comment]
@QNetITQ Is requiring to disable the accent color deliberate? If not, would it be possible to remove this limitation? The CSS from https://www.reddit.com/r/FirefoxCSS/comments/tpkz9v/windows_11_mica_acrylic_for_firefox/ is able to keep transparency while accent colors are enabled.

**Comment by QNetITQ** [comment]
This is not a limitation. It's done on purpose. Users typically use transparency with no accent, or accent with no transparency. If you want system effects to always work, just delete lines 36, 37, 66.
[windows_11_10.css](https://github.com/QNetITQ/WaveFox/blob/3e4c5c9156004f7298d07ea306ee10073b27f1cf/chrome/special/windows_11_10.css#L36)
