### ISSUE TITLE
Wrong tab background when switching with CTRL+TAB

### ISSUE THREAD

**Issue by kocane** [QNetITQ/WaveFox#9]
I've noticed when switching tabs with CTRL+TAB, sometimes the tab that is switched to seems to flicker for a very, very brief moment. It does however look kind of odd, so I recorded it and freeze framed. It looks like this:
![image](https://user-images.githubusercontent.com/7694813/131382049-0cc05dbc-5351-48f8-8fcd-04998a7db73e.png)
So seemingly, it's both the previous (right) and "switched to" tab (left) that gets the wrong background for a split second.

Reckon anything can be done about it?

**Comment by QNetITQ** [comment]
Hi. I understand what you are talking about. This is how the browser compositing system works. The tab consists of raster and vector graphics. It looks like compositing renders them differently. Only Mozilla can fix it

**Comment by QNetITQ** [comment]
Judging by your screen, the selected tab didn't even change the font color to black. Perhaps JavaScript takes precedence over CSS and its processing slows down rendering

**Comment by QNetITQ** [comment]
I can try to hide the uneven rendering. This is a terrible crutch, of course, but it might help. In the next release I will do

**Comment by kocane** [comment]
> I can try to hide the uneven rendering. This is a terrible crutch, of course, but it might help. In the next release I will do 

Thanks, I'll try it out when you release it.

It's obviously not a huge deal but we can hardly expect that Mozilla will actually fix the underlying issue, do you think?

**Comment by QNetITQ** [comment]
Localized the problem. The style is to blame. True, the fix is very simple. I'll post it most likely today, just make some more changes

**Comment by QNetITQ** [comment]
It seems to be fixed. Check

**Comment by kocane** [comment]
I agree confirm that the issue is fixed.

Thanks! 😄
