### ISSUE TITLE
Windows 11 System Effects

### ISSUE THREAD

**Issue by indue4482** [QNetITQ/WaveFox#90]
I am using Windows 11 22H2 and Firefox 107. Using System Effects for WaveFox is not working, it is just a solid color depends on your theme's one.

![SS](https://user-images.githubusercontent.com/70325669/202716151-72ef9093-65a2-49dd-b135-4dd60fb2b167.png)

**Comment by indue4482** [comment]
Not working in Nightly tho.

**Comment by QNetITQ** [comment]
Windows 11 itself does not support transparency for desktop apps. More precisely, it partially supports. Requires [Mica For Everyone](https://github.com/MicaForEveryone/MicaForEveryone/releases). You have already prepared a browser for working with transparency.

**Comment by indue4482** [comment]
Understandable. I thought Windows 11 supports it when i saw the "System effects must be supported on the operating system side" section.
