### ISSUE TITLE
Proton Tabs background color

### ISSUE THREAD

**Issue by fieraoh** [QNetITQ/WaveFox#92]
Would you please consider making the proton tabs use their default color as in here.

![image](https://user-images.githubusercontent.com/72320316/202876394-4018410b-fb76-45f5-aa1b-b7d34b75fb84.png)

Though enabling a border does improve visibility for the active tab, it is still not optimal. Proton tabs without a border are hardly distinguishable.

![image](https://user-images.githubusercontent.com/72320316/202876458-b3402d6e-e024-4a5e-90b5-baede8c44e4b.png)

**Comment by QNetITQ** [comment]
Try it. If you don't like it, I'll roll back the change.

**Comment by fieraoh** [comment]
It is perfect, thank you.
