### ISSUE TITLE
All extensions are automatically moved to the overflow menu

### ISSUE THREAD

**Issue by dreamsynth** [QNetITQ/WaveFox#95]
In the toolbar settings everything is displayed as it should be - all the extensions are in their places, but when you exit the toolbar settings, they are automatically moved to the overflow menu

**Comment by QNetITQ** [comment]
Need more info on style settings.

**Comment by dreamsynth** [comment]
It turned out that the problem is not in your style, but in this piece of code from my additional css file: 

```
#forward-button[disabled="true"] {
  visibility: collapse !important;
}

forward-button:not([disabled="true"]) {
  visibility: visible !important;
}
```

it hides the forward button when it is disabled. I have no idea why this also hides extension buttons.

Anyway, thank you. You're developing the best CSS-style for Firefox. Keep up the good work!
