### ISSUE TITLE
Toolbar color changed in the latest Firefox Nightly

### ISSUE THREAD

**Issue by 1F357** [QNetITQ/WaveFox#97]
WavaFox is amazing, thank you for your great work! It gives me much more customization options for my Firefox.

I haven't used my computer for the last few days,  and when I updated Firefox Nightly to the latest version , the color of the Toolbar changed. It was black before, but now it's gray.

I tried to update WaveFox to the latest version, but the color doesn't seem to change back to black.

This is a screenshot of a previous version of Firefox Nightly with WaveFox, I'm sorry I can't remember the exact Firefox version this screenshot corresponds to, maybe 108?
![0FBD0FB2F0A8E3C24D84ED8CE5B86991](https://user-images.githubusercontent.com/105695590/209441372-27be35c1-3f36-49cf-bbda-a5a79ae9fa2d.png)

This is a screenshot of the latest version of Firefox Nightly(110.0a1 (2022-12-24)) with WaveFox, you can notice that the color of Toolbar has changed.
![QQ截图20221224224010](https://user-images.githubusercontent.com/105695590/209441444-14277b5c-29ad-490f-8170-b8f5b98fedc9.png)

Here are the features of WaveFox that I have activated

> - toolkit.legacyUserProfileCustomizations.stylesheets
> - layout.css.color-mix.enabled
> - userChrome.PhotonTabs-Enabled
> - userChrome.WindowsSystemEffects-Enabled
> - userChrome.TabSeparators-Enabled
> - userChrome.RegularMenuIcons-Enabled
> - userChrome.DragSpaceAboveTabsWindowedMode-Disabled

Is there something wrong with my configuration, or is there some adjustments in the Firefox updates? I'm sorry I don't know much about customizing the appearance of the browser. If there is a way to change the color of the ToolBar back? Thank you very much!

Some other information:
> Windows 11 22H2
> Mica For Everyone 1.2.0.0
> Firefox Nightly 110.0a1 (2022-12-24) (64 bit)

**Comment by QNetITQ** [comment]
[Reddit_1](https://www.reddit.com/r/firefox/comments/zsnyw9/new_default_dark_theme_looks_really_bad_in_latest/)
[Reddit_2](https://www.reddit.com/r/firefox/comments/ztecpx/new_firefox_nightly_dark_theme_does_anyone_like_it/)

**Comment by 1F357** [comment]
> [Reddit_1](https://www.reddit.com/r/firefox/comments/zsnyw9/new_default_dark_theme_looks_really_bad_in_latest/) [Reddit_2](https://www.reddit.com/r/firefox/comments/ztecpx/new_firefox_nightly_dark_theme_does_anyone_like_it/)

Oh my god, I can't believe this is an official change by Mozilla😂
