### ISSUE TITLE
How to remove Photon tabs top gap

### ISSUE THREAD

**Issue by restfuladi** [QNetITQ/WaveFox#99]
First, thanks for proving this public service. I love the look of the photon tabs, if I could remove the gap between the active tab rectangle and the top of the window it would look perfect in i3.

**Comment by QNetITQ** [comment]
`userChrome.DragSpaceAboveTabsWindowedMode-Disabled`

**Comment by restfuladi** [comment]
Thanks, I added that bool and I still see this:
![image](https://user-images.githubusercontent.com/14058796/210109917-0733853f-5899-4d80-9fed-1eb2c5171fce.png)

**Comment by QNetITQ** [comment]
By default, the drag space is active in windowed mode. It is disabled in pseudo-fullscreen and fullscreen. The keys allow you to change these values to the opposite. Focus on their names.

`userChrome.DragSpaceAboveTabsWindowedMode-Disabled`
`userChrome.DragSpaceAboveTabsMaximizedMode-Enabled`
`userChrome.DragSpaceAboveTabsFullscreenMode-Enabled`

If that doesn't work, the title bar may be active. Then it needs to be turned off.

`browser.tabs.inTitlebar` > 1

**Comment by restfuladi** [comment]
I set `userChrome.DragSpaceAboveTabsWindowedMode-Disabled` to true and `browser.tabs.inTitlebar` is already set to 2. Not sure what I'm doing wrong.

**Comment by QNetITQ** [comment]
Then there is a temporary way, it will definitely work. Go to `chrome/special/linux.css`. Find this [line](https://github.com/QNetITQ/WaveFox/blob/f6f3da53be44bc3d33f72035535b1a01fdd5728b/chrome/special/linux.css#L71) and change the value to 0px.
I'll redo it for the release of Firefox 110.

**Comment by restfuladi** [comment]
Works, thanks!
